# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



SHELL = /bin/sh

srcdir = .
top_srcdir = ..

prefix = /home/riscos/cross/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/gettext
pkglibdir = $(libdir)/gettext
pkgincludedir = $(includedir)/gettext
top_builddir = ..

ACLOCAL = ${SHELL} /home/cross/libraries/gettext-0.11.5/missing --run aclocal
AUTOCONF = ${SHELL} /home/cross/libraries/gettext-0.11.5/missing --run autoconf
AUTOMAKE = ${SHELL} /home/cross/libraries/gettext-0.11.5/missing --run automake
AUTOHEADER = ${SHELL} /home/cross/libraries/gettext-0.11.5/missing --run autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = arm-riscos-aof
host_triplet = arm-riscos-aof
AMTAR = ${SHELL} /home/cross/libraries/gettext-0.11.5/missing --run tar
AS = as
AWK = mawk
BUILDJAVA = no
BUILDJAVAEXE = no
BUILD_INCLUDED_LIBINTL = yes
CATOBJEXT = .gmo
CC = gcc
CLASSPATH = 
CLASSPATH_SEPARATOR = :
CROSS_COMPILING = yes
CXX = c++
DATADIRNAME = share
DEPDIR = .deps
DLLTOOL = dlltool
DVIPS = /home/cross/libraries/gettext-0.11.5/missing dvips
ECHO = echo
EMACS = emacs
EXEEXT = 
GCC = yes
GCJ = none
GCJFLAGS = 
GENCAT = gencat
GLIBC21 = no
GMSGFMT = /usr/bin/msgfmt
HAVE_GCJ = 
HAVE_GCJ_C = 
HAVE_GCJ_IN_PATH = 
HAVE_GIJ = 
HAVE_GIJ_IN_PATH = 
HAVE_JAVA = 
HAVE_JAVAC = 
HAVE_JAVAC_IN_PATH = 
HAVE_JAVA_IN_PATH = 
HAVE_JIKES = 
HAVE_JIKES_IN_PATH = 
HAVE_JRE = 
HAVE_JRE_IN_PATH = 
HAVE_JVIEW = 
HAVE_JVIEW_IN_PATH = 
HAVE_LIB = @HAVE_LIB@
HAVE__BOOL = 0
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
INSTOBJEXT = .mo
INTLBISON = bison
INTLLIBS = ${top_builddir}/intl/libintl.la 
INTLOBJS = $(GETTOBJS)
INTL_LIBTOOL_SUFFIX_PREFIX = l
JAR = 
JAVA = 
JAVAC = 
LD = /home/riscos/cross-7.7.2002/bin/arm-riscos-aof/2_95_4/ld
LEX = flex
LEX_OUTPUT_ROOT = lex.yy
LIB = @LIB@
LIBEXPAT = /home/riscos/cross/local/lib/libexpat.a
LIBICONV = 
LIBINTL = ${top_builddir}/intl/libintl.la 
LIBOBJS =  vasprintf.o getline.o pfnmatch.o mkdtemp.o
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
LTALLOCA = 
LTLIB = @LTLIB@
LTLIBEXPAT = -L/home/riscos/cross/local/lib -lexpat
LTLIBICONV = 
LTLIBINTL = ${top_builddir}/intl/libintl.la 
LTLIBOBJS =  vasprintf.lo getline.lo pfnmatch.lo mkdtemp.lo
MKINSTALLDIRS = ./mkinstalldirs
OBJDUMP = objdump
OBJEXT = o
PACKAGE = gettext
PERL = /usr/bin/perl
POSUB = po
RANLIB = ranlib
STDBOOL_H = stdbool.h
STRIP = strip
TESTJAVA = no
TEXI2PDF = /home/cross/libraries/gettext-0.11.5/missing texi2pdf
USE_INCLUDED_LIBINTL = yes
USE_NLS = yes
VERSION = 0.11.5
YACC = bison -y
aclocaldir = ${datadir}/aclocal
am__include = include
am__quote = 
install_sh = /home/cross/libraries/gettext-0.11.5/install-sh
lispdir = ${datadir}/emacs/site-lisp
with_gnu_ld = no

AUTOMAKE_OPTIONS = 1.5 gnits no-dependencies

TESTS = gettext-1 gettext-2 \
	msgattrib-1 msgattrib-2 msgattrib-3 msgattrib-4 msgattrib-5 \
	msgattrib-6 msgattrib-7 msgattrib-8 msgattrib-9 msgattrib-10 \
	msgattrib-11 msgattrib-12 msgattrib-13 msgattrib-14 \
	msgcat-1 msgcat-2 msgcat-3 msgcat-4 msgcat-5 msgcat-6 msgcat-7 \
	msgcmp-1 msgcmp-2 \
	msgcomm-1 msgcomm-2 msgcomm-3 msgcomm-4 msgcomm-5 msgcomm-6 msgcomm-7 \
	msgcomm-8 msgcomm-9 msgcomm-10 msgcomm-11 msgcomm-12 msgcomm-13 \
	msgcomm-14 msgcomm-15 msgcomm-16 msgcomm-17 msgcomm-18 msgcomm-19 \
	msgcomm-20 msgcomm-21 msgcomm-22 msgcomm-23 \
	msgconv-1 msgconv-2 msgconv-3 \
	msgen-1 \
	msgexec-1 msgexec-2 \
	msgfilter-1 msgfilter-2 \
	msgfmt-1 msgfmt-2 msgfmt-3 msgfmt-4 msgfmt-5 msgfmt-6 msgfmt-7 \
	msgfmt-8 msgfmt-9 msgfmt-10 msgfmt-11 msgfmt-12 \
	msggrep-1 msggrep-2 msggrep-3 msggrep-4 msggrep-5 \
	msgmerge-1 msgmerge-2 msgmerge-3 msgmerge-4 msgmerge-5 msgmerge-6 \
	msgmerge-7 msgmerge-8 msgmerge-9 msgmerge-10 msgmerge-11 msgmerge-12 \
	msgmerge-13 msgmerge-14 msgmerge-15 msgmerge-16 msgmerge-17 \
	msgmerge-18 msgmerge-19 msgmerge-20 \
	msgunfmt-1 msgunfmt-2 msgunfmt-3 \
	msguniq-1 msguniq-2 msguniq-3 \
	xgettext-1 xgettext-2 xgettext-3 xgettext-4 xgettext-5 xgettext-6 \
	xgettext-7 xgettext-8 xgettext-9 xgettext-10 xgettext-11 xgettext-12 \
	xgettext-13 xgettext-14 xgettext-15 xgettext-16 xgettext-17 \
	xgettext-18 xgettext-19 xgettext-20 xgettext-21 xgettext-22 \
	format-awk-1 format-awk-2 \
	format-c-1 format-c-2 format-c-3 format-c-4 \
	format-elisp-1 format-elisp-2 \
	format-java-1 format-java-2 \
	format-librep-1 format-librep-2 \
	format-lisp-1 format-lisp-2 \
	format-python-1 format-python-2 \
	format-pascal-1 format-pascal-2 \
	format-tcl-1 format-tcl-2 \
	format-ycp-1 format-ycp-2 \
	plural-1 plural-2 \
	lang-c lang-c++ lang-objc lang-python lang-clisp lang-elisp lang-librep lang-java lang-gawk lang-pascal lang-ycp lang-tcl lang-po lang-rst \
	rpath-1a rpath-1b \
	rpath-2aaa rpath-2aab rpath-2aac rpath-2aad \
	rpath-2aba rpath-2abb rpath-2abc rpath-2abd \
	rpath-2baa rpath-2bab rpath-2bac rpath-2bad \
	rpath-2bba rpath-2bbb rpath-2bbc rpath-2bbd \
	rpath-3aaa rpath-3aab rpath-3aac rpath-3aad \
	           rpath-3aaf            rpath-3aah \
	rpath-3aba rpath-3abb rpath-3abc rpath-3abd \
	           rpath-3abf            rpath-3abh \
	rpath-3baa rpath-3bab rpath-3bac rpath-3bad \
	rpath-3bae rpath-3baf rpath-3bag rpath-3bah \
	rpath-3bba rpath-3bbb rpath-3bbc rpath-3bbd \
	rpath-3bbe rpath-3bbf rpath-3bbg rpath-3bbh


EXTRA_DIST = $(TESTS) \
	test.mo xg-test1.ok.po mex-test2.ok msguniq-a.in msguniq-a.out \
	rpathx/configure.in rpathx/aclocal.m4 rpathx/configure \
	rpathx/Makefile.am rpathx/Makefile.in rpathx/rpathx.c \
	rpathy/configure.in rpathy/aclocal.m4 rpathy/configure \
	rpathy/Makefile.am rpathy/Makefile.in rpathy/rpathy.c \
	rpathz/configure.in rpathz/aclocal.m4 rpathz/configure \
	rpathz/Makefile.am rpathz/Makefile.in rpathz/rpathz.c \
	rpathlx/configure.in rpathlx/aclocal.m4 rpathlx/configure \
	rpathlx/Makefile.am rpathlx/Makefile.in rpathlx/usex.c \
	rpathly/configure.in rpathly/aclocal.m4 rpathly/configure \
	rpathly/Makefile.am rpathly/Makefile.in rpathly/usey.c \
	rpathlyx/configure.in rpathlyx/aclocal.m4 rpathlyx/configure \
	rpathlyx/Makefile.am rpathlyx/Makefile.in rpathlyx/usey.c \
	rpathlz/configure.in rpathlz/aclocal.m4 rpathlz/configure \
	rpathlz/Makefile.am rpathlz/Makefile.in rpathlz/usez.c \
	rpathlzyx/configure.in rpathlzyx/aclocal.m4 rpathlzyx/configure \
	rpathlzyx/Makefile.am rpathlzyx/Makefile.in rpathlzyx/usez.c \
	rpath-1 rpath-2_a rpath-2_b rpath-3_a rpath-3_b rpath.README \
	rpath-3aae rpath-3aag rpath-3abe rpath-3abg \
	rpathcfg.sh


XGETTEXT = ../src/xgettext

TESTS_ENVIRONMENT = top_srcdir=$(top_srcdir) PATH=.:../src:$$PATH \
		    GETTEXT=tstgettext \
		    NGETTEXT=tstngettext \
		    XGETTEXT=xgettext \
		    MSGATTRIB=msgattrib \
		    MSGCAT=msgcat \
		    MSGCMP=msgcmp \
		    MSGCOMM=msgcomm \
		    MSGCONV=msgconv \
		    MSGEN=msgen \
		    MSGEXEC=msgexec \
		    MSGFILTER=msgfilter \
		    MSGFMT=msgfmt \
		    MSGGREP=msggrep \
		    MSGMERGE=msgmerge \
		    MSGUNFMT=msgunfmt \
		    MSGUNIQ=msguniq \
		    OBJEXT='o' EXEEXT='' \
		    LIBTOOL='$(SHELL) $(top_builddir)/libtool' \
		    CC='gcc' CFLAGS='-D_INTL_REDIRECT_MACROS' \
		    CXX='c++' CXXFLAGS='' \
		    CPPFLAGS='-I/home/riscos/cross/local/include' LDFLAGS='' \
		    LTLIBINTL='${top_builddir}/intl/libintl.la ' \
		    TESTJAVA='no' \
		    CONFIG_SHELL='$(SHELL)' \
		    $(SHELL)


# Three auxiliary programs used by the tests.
INCLUDES = -I.. -I../lib -I$(top_srcdir)/lib -I$(top_srcdir)/intl
DEFS = -DLOCALEDIR=\"$(localedir)\" -DHAVE_CONFIG_H
LDADD = $(LDADD_yes)
LDADD_yes = ../intl/libintl.la
LDADD_no = ../intl/libgnuintl.la ${top_builddir}/intl/libintl.la 
noinst_PROGRAMS = tstgettext tstngettext cake fc3 fc4
tstgettext_SOURCES = tstgettext.c setlocale.c
tstgettext_LDADD = ../lib/libgettextlib.la $(LDADD)
tstngettext_SOURCES = tstngettext.c setlocale.c
tstngettext_LDADD = ../lib/libgettextlib.la $(LDADD)
cake_SOURCES = plural-1-prg.c setlocale.c
cake_LDADD = ../lib/libgettextlib.la $(LDADD)
fc3_SOURCES = format-c-3-prg.c setlocale.c
fc3_LDADD = ../lib/libgettextlib.la $(LDADD)
fc4_SOURCES = format-c-4-prg.c setlocale.c
fc4_LDADD = ../lib/libgettextlib.la $(LDADD)
MOSTLYCLEANFILES = rpathcfg rpathcfg.log
subdir = tests
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
noinst_PROGRAMS = tstgettext$(EXEEXT) tstngettext$(EXEEXT) cake$(EXEEXT) \
	fc3$(EXEEXT) fc4$(EXEEXT)
PROGRAMS = $(noinst_PROGRAMS)

am_cake_OBJECTS = plural-1-prg.$(OBJEXT) setlocale.$(OBJEXT)
cake_OBJECTS = $(am_cake_OBJECTS)
cake_DEPENDENCIES = ../lib/libgettextlib.la
cake_LDFLAGS =
am_fc3_OBJECTS = format-c-3-prg.$(OBJEXT) setlocale.$(OBJEXT)
fc3_OBJECTS = $(am_fc3_OBJECTS)
fc3_DEPENDENCIES = ../lib/libgettextlib.la
fc3_LDFLAGS =
am_fc4_OBJECTS = format-c-4-prg.$(OBJEXT) setlocale.$(OBJEXT)
fc4_OBJECTS = $(am_fc4_OBJECTS)
fc4_DEPENDENCIES = ../lib/libgettextlib.la
fc4_LDFLAGS =
am_tstgettext_OBJECTS = tstgettext.$(OBJEXT) setlocale.$(OBJEXT)
tstgettext_OBJECTS = $(am_tstgettext_OBJECTS)
tstgettext_DEPENDENCIES = ../lib/libgettextlib.la
tstgettext_LDFLAGS =
am_tstngettext_OBJECTS = tstngettext.$(OBJEXT) setlocale.$(OBJEXT)
tstngettext_OBJECTS = $(am_tstngettext_OBJECTS)
tstngettext_DEPENDENCIES = ../lib/libgettextlib.la
tstngettext_LDFLAGS =
DEFAULT_INCLUDES =  -I. -I$(srcdir) -I$(top_builddir)
CPPFLAGS = -I/home/riscos/cross/local/include
LDFLAGS = 
LIBS = 
depcomp =
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) \
	$(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
CFLAGS = -D_INTL_REDIRECT_MACROS
DIST_SOURCES = $(cake_SOURCES) $(fc3_SOURCES) $(fc4_SOURCES) \
	$(tstgettext_SOURCES) $(tstngettext_SOURCES)
DIST_COMMON = ChangeLog Makefile.am Makefile.in
SOURCES = $(cake_SOURCES) $(fc3_SOURCES) $(fc4_SOURCES) $(tstgettext_SOURCES) $(tstngettext_SOURCES)

all: all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnits  tests/Makefile
Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	  CONFIG_HEADERS= CONFIG_LINKS= \
	  CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)
cake$(EXEEXT): $(cake_OBJECTS) $(cake_DEPENDENCIES) 
	@rm -f cake$(EXEEXT)
	$(LINK) $(cake_LDFLAGS) $(cake_OBJECTS) $(cake_LDADD) $(LIBS)
fc3$(EXEEXT): $(fc3_OBJECTS) $(fc3_DEPENDENCIES) 
	@rm -f fc3$(EXEEXT)
	$(LINK) $(fc3_LDFLAGS) $(fc3_OBJECTS) $(fc3_LDADD) $(LIBS)
fc4$(EXEEXT): $(fc4_OBJECTS) $(fc4_DEPENDENCIES) 
	@rm -f fc4$(EXEEXT)
	$(LINK) $(fc4_LDFLAGS) $(fc4_OBJECTS) $(fc4_LDADD) $(LIBS)
tstgettext$(EXEEXT): $(tstgettext_OBJECTS) $(tstgettext_DEPENDENCIES) 
	@rm -f tstgettext$(EXEEXT)
	$(LINK) $(tstgettext_LDFLAGS) $(tstgettext_OBJECTS) $(tstgettext_LDADD) $(LIBS)
tstngettext$(EXEEXT): $(tstngettext_OBJECTS) $(tstngettext_DEPENDENCIES) 
	@rm -f tstngettext$(EXEEXT)
	$(LINK) $(tstngettext_LDFLAGS) $(tstngettext_OBJECTS) $(tstngettext_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

.c.o:
	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.c.lo:
	$(LTCOMPILE) -c -o $@ $<
uninstall-info-am:

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH

check-TESTS: $(TESTS)
	@failed=0; all=0; xfail=0; xpass=0; \
	srcdir=$(srcdir); export srcdir; \
	list='$(TESTS)'; \
	if test -n "$$list"; then \
	  for tst in $$list; do \
	    if test -f ./$$tst; then dir=./; \
	    elif test -f $$tst; then dir=; \
	    else dir="$(srcdir)/"; fi; \
	    if $(TESTS_ENVIRONMENT) $${dir}$$tst; then \
	      all=`expr $$all + 1`; \
	      case " $(XFAIL_TESTS) " in \
	      *" $$tst "*) \
	        xpass=`expr $$xpass + 1`; \
	        failed=`expr $$failed + 1`; \
	        echo "XPASS: $$tst"; \
	      ;; \
	      *) \
	        echo "PASS: $$tst"; \
	      ;; \
	      esac; \
	    elif test $$? -ne 77; then \
	      all=`expr $$all + 1`; \
	      case " $(XFAIL_TESTS) " in \
	      *" $$tst "*) \
	        xfail=`expr $$xfail + 1`; \
	        echo "XFAIL: $$tst"; \
	      ;; \
	      *) \
	        failed=`expr $$failed + 1`; \
	        echo "FAIL: $$tst"; \
	      ;; \
	      esac; \
	    fi; \
	  done; \
	  if test "$$failed" -eq 0; then \
	    if test "$$xfail" -eq 0; then \
	      banner="All $$all tests passed"; \
	    else \
	      banner="All $$all tests behaved as expected ($$xfail expected failures)"; \
	    fi; \
	  else \
	    if test "$$xpass" -eq 0; then \
	      banner="$$failed of $$all tests failed"; \
	    else \
	      banner="$$failed of $$all tests did not behave as expected ($$xpass unexpected passes)"; \
	    fi; \
	  fi; \
	  dashes=`echo "$$banner" | sed s/./=/g`; \
	  echo "$$dashes"; \
	  echo "$$banner"; \
	  echo "$$dashes"; \
	  test "$$failed" -eq 0; \
	fi

DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = ..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	$(mkinstalldirs) $(distdir)/rpathlx $(distdir)/rpathly $(distdir)/rpathlyx $(distdir)/rpathlz $(distdir)/rpathlzyx $(distdir)/rpathx $(distdir)/rpathy $(distdir)/rpathz
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    $(mkinstalldirs) "$(distdir)/$$dir"; \
	  fi; \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
check: check-am
all-am: Makefile $(PROGRAMS)

installdirs:

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:
	-test -z "$(MOSTLYCLEANFILES)" || rm -f $(MOSTLYCLEANFILES)

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libtool clean-noinstPROGRAMS \
	mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-compile distclean-generic \
	distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am:

install-exec-am:

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

uninstall-am: uninstall-info-am

.PHONY: GTAGS all all-am check check-TESTS check-am clean clean-generic \
	clean-libtool clean-noinstPROGRAMS distclean distclean-compile \
	distclean-generic distclean-libtool distclean-tags distdir dvi \
	dvi-am info info-am install install-am install-data \
	install-data-am install-exec install-exec-am install-info \
	install-info-am install-man install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool tags uninstall \
	uninstall-am uninstall-info-am


xg-test1.ok.po: $(top_srcdir)/src/xgettext.c $(top_srcdir)/src/msgfmt.c \
		$(top_srcdir)/src/gettext.c
	$(XGETTEXT) -d xg-test1.ok -p $(srcdir) \
	  -k_ --omit-header --no-location \
	  $(top_srcdir)/src/xgettext.c $(top_srcdir)/src/msgfmt.c \
	  $(top_srcdir)/src/gettext.c

# Help maintaining config.rpath.
rpathcfg: rpathcfg.sh
	top_srcdir=$(top_srcdir) \
	CONFIG_SHELL='$(SHELL)' \
	CC='gcc' GCC='yes' \
	LDFLAGS='' \
	LD='/home/riscos/cross-7.7.2002/bin/arm-riscos-aof/2_95_4/ld' with_gnu_ld='no' \
	host='arm-riscos-aof' \
	$(SHELL) $(srcdir)/rpathcfg.sh > rpathcfg 2> rpathcfg.log
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
