#!/bin/sh

LIBXML=libxml2-2.6.22

if [ -n "$1" ]; then
 PREFIX=$1
else
 PREFIX=/home/riscos/cross/local
fi

rm -rf $LIBXML
tar -xzf $LIBXML.tar.gz

export ac_cv_prog_cc_g=no
export lt_cv_prog_cc_can_build_shared=no
export lt_cv_prog_cc_pic_works=no
export c_cv_working_getnameinfo=no
export c_cv_func_getaddrinfo=no


(cd $LIBXML; \
ro-config --prefix=$PREFIX \
--enable-ipv6=no \
--with-zlib=$PREFIX \
--with-iconv=$PREFIX \
&& make && make install) || exit 1

