#!/bin/sh

LIBXSLT=libxslt-1.1.6

if [ -n "$1" ]; then
 PREFIX=$1
else
 PREFIX=/home/riscos/cross/local
fi

cat > $LIBXSLT/config.cache << EOF
ac_cv_prog_cc_g=\${ac_cv_prog_cc_g=no}
lt_cv_prog_cc_can_build_shared=\${lt_cv_prog_cc_can_build_shared=no}
lt_cv_prog_cc_pic_works=\${lt_cv_prog_cc_pic_works=no}
ac_cv_working_getnameinfo=\${ac_cv_working_getnameinfo=no}
ac_cv_func_getaddrinfo=\${ac_cv_func_getaddrinfo=no}
EOF


(cd $LIBXSLT; \
./configure --host=arm-riscos-aof --prefix=$PREFIX \
  --with-libxml-prefix=$PREFIX \
  --with-libxml-include-prefix=$PREFIX \
  --with-libxml-libs-prefix=$PREFIX \
&& make clean && make && make install) || exit 1

