#!/bin/sh

EXPAT=expat-1.95.4

if [ -n "$1" ]; then
 PREFIX=$1
else
 PREFIX=/home/riscos/cross/local
fi


(cd $EXPAT; \
./configure --host=arm-riscos-aof --prefix=$PREFIX \
&& make clean && make && make install) || exit 1

