#!/bin/sh
#
# Usage: build [prefix]
#

ZLIB=zlib-1.1.4
LIBPNG=libpng-1.2.5
REGEX=regex
LIBJPEG=jpeg-6b
LIBGD=gd-1.8.4
GETTEXT=gettext-0.11.5

if [ -n "$1" ]; then
 PREFIX=$1
else
 PREFIX=/home/riscos/cross/local
fi

mkdir -p $PREFIX/bin $PREFIX/lib

./build-zlib   $PREFIX || exit 1

(cd $LIBPNG; \
make clean && make PREFIX=$PREFIX && make install PREFIX=$PREFIX) || exit 1

(cd $LIBJPEG; \
./configure --host=arm-riscos-aof --prefix=$PREFIX \
&& make clean && make && make install-lib) || exit 1

(cd $LIBGD; \
make clean && make PREFIX=$PREFIX && make install PREFIX=$PREFIX) || exit 1

(cd $REGEX; \
make clean && make && make install PREFIX=$PREFIX) || exit 1

./build-oslib   $PREFIX || exit 1
./build-openssl $PREFIX || exit 1
./build-expat   $PREFIX || exit 1
./build-neon    $PREFIX || exit 1
./build-apr     $PREFIX || exit 1
./build-aprutil $PREFIX || exit 1


exit 0

(cd $GETTEXT; \
./configure --with-included-gettext \
--host=arm-riscos-aof --prefix=$PREFIX \
&& make clean && make && make install) || exit 1
