#!/bin/sh

NEON=neon-0.24.7

if [ -n "$1" ]; then
 PREFIX=$1
else
 PREFIX=/home/riscos/cross/local
fi

rm -rf $NEON
tar -xzf $NEON.tar.gz || exit 1


cat > $NEON/config.cache << EOF
ac_cv_prog_cc_g=\${ac_cv_prog_cc_g=no}
lt_cv_prog_cc_can_build_shared=\${lt_cv_prog_cc_can_build_shared=no}
lt_cv_prog_cc_pic_works=\${lt_cv_prog_cc_pic_works=no}
EOF

(cd $NEON; \
./configure --host=arm-riscos-aof -C --prefix=$PREFIX \
--with-libs=$PREFIX --with-force-zlib --with-ssl \
&& make && make install) || exit 1
