#!/bin/sh

LIBXML=libxml2-2.6.9

if [ -n "$1" ]; then
 PREFIX=$1
else
 PREFIX=/home/riscos/cross/local
fi

cat > $LIBXML/config.cache << EOF
ac_cv_prog_cc_g=\${ac_cv_prog_cc_g=no}
lt_cv_prog_cc_can_build_shared=\${lt_cv_prog_cc_can_build_shared=no}
lt_cv_prog_cc_pic_works=\${lt_cv_prog_cc_pic_works=no}
ac_cv_working_getnameinfo=\${ac_cv_working_getnameinfo=no}
ac_cv_func_getaddrinfo=\${ac_cv_func_getaddrinfo=no}
EOF


(cd $LIBXML; \
./configure --host=arm-riscos-aof --prefix=$PREFIX \
--enable-ipv6=no \
--with-zlib=$PREFIX \
--with-iconv=$PREFIX \
&& touch Makefile.in \
&& touch configure.in \
&& touch config.h.in \
&& touch configure \
&& make clean && make && make install) || exit 1

