#!/bin/sh

OPENSSL=openssl-0.9.7e

if [ -n "$1" ]; then
 PREFIX=$1
else
 PREFIX=/home/riscos/cross/local
fi

mkdir -p $PREFIX

rm -rf $OPENSSL
tar -xzf $OPENSSL.tar.gz

(cd $OPENSSL \
&& ./Configure --prefix=$PREFIX -DNO_SYS_UN_H gcc \
&& make && make install) || exit 1
