#!/bin/sh

GETTEXT=gettext-0.11.5

if [ -n "$1" ]; then
 PREFIX=$1
else
 PREFIX=/home/riscos/cross/local
fi

rm -rf $GETTEXT
tar -xzf $GETTEXT.tar.gz

(cd $GETTEXT; \
./configure --with-included-gettext \
--host=arm-riscos-aof --prefix=$PREFIX \
&& make clean && make && make install) || exit 1
