#!/bin/sh

NEON=neon-0.28.3

if [ -n "$1" ]; then
 PREFIX=$1
else
 PREFIX=/home/riscos/env
fi

rm -rf $NEON
tar -xzf $NEON.tar.gz || exit 1


export ac_cv_func_getaddrinfo=no

(cd $NEON; \
CFLAGS=-mpoke-function-name \
ro-config --prefix=$PREFIX \
--with-libs=$PREFIX --with-force-zlib --with-ssl \
&& make && make install) || exit 1
