#!/bin/sh
#
# Usage: build [prefix [32]]
#

OPENSSL=openssl-0.9.6g
NEON=neon-0.23.5
EXPAT=expat-1.95.4
ZLIB=zlib-1.1.4 
LIBPNG=libpng-1.2.5
REGEX=regex
LIBJPEG=jpeg-6b
LIBGD=gd-1.8.4
APR=apr
APRUTIL=apr-util
GETTEXT=gettext-0.11.5

if [ -n "$1" ]; then
 PREFIX=$1
else
 PREFIX=/home/riscos/cross/local
fi 

BUILD=$2

mkdir -p $PREFIX/include $PREFIX/lib || exit 1

# Remove pthread.h if it is a dummy header
PTHREAD=/home/riscos/cross/include/unixlib/pthread.h
#grep pthread_t $PTHREAD || rm -f $PTHREAD
# pthreads not happy with apr yet
rm -f $PTHREAD

rm -f $PREFIX/include/oslib*
rm -f $PREFIX/lib/liboslib*

ln -s `pwd`/oslib/oslib $PREFIX/include/oslib
ln -s `pwd`/oslibsupport/oslibsupport $PREFIX/include/oslibsupport
ln -s `pwd`/oslib/OSLib${BUILD}.o $PREFIX/lib/liboslib.o
ln -s `pwd`/oslibsupport/OSLibSupport${BUILD}.o $PREFIX/lib/liboslibsupport.o

(cd $ZLIB; ./configure --prefix=$PREFIX \
&& make clean && make && make install) || exit 1

(cd $OPENSSL; ./Configure --prefix=$PREFIX \
-DNO_SYS_UN_H \
gcc && make clean && make && make install) || exit 1

(cd $EXPAT; \
./configure --host=arm-riscos-aof --prefix=$PREFIX \
&& make clean && make && make install) || exit 1

(cd $LIBPNG; \
make clean && make PREFIX=$PREFIX && make install PREFIX=$PREFIX) || exit 1

(cd $LIBJPEG; \
./configure --host=arm-riscos-aof --prefix=$PREFIX \
&& make clean && make && make install-lib) || exit 1

(cd $LIBGD; \
make clean && make PREFIX=$PREFIX && make install PREFIX=$PREFIX) || exit 1

(cd $REGEX; \
make clean && make && make install PREFIX=$PREFIX) || exit 1

cat > $NEON/config.cache << EOF
ac_cv_prog_cc_g=\${ac_cv_prog_cc_g=no}
lt_cv_prog_cc_can_build_shared=\${lt_cv_prog_cc_can_build_shared=no}
lt_cv_prog_cc_pic_works=\${lt_cv_prog_cc_pic_works=no}
ne_cv_lib_sslegd=\${ne_cv_lib_sslegd=yes}
EOF

(cd $NEON; \
./configure --host=arm-riscos-aof -C --prefix=$PREFIX \
--with-libs=$PREFIX --with-force-zlib --with-ssl \
&& make clean && make && make install) || exit 1


cat > $APR/config.cache << EOF
ac_cv_prog_cc_g=\${ac_cv_prog_cc_g=no}
lt_cv_prog_cc_can_build_shared=\${lt_cv_prog_cc_can_build_shared=no}
lt_cv_prog_cc_pic_works=\${lt_cv_prog_cc_pic_works=no}
ac_cv_sizeof_off_t=\${ac_cv_sizeof_off_t=4}
ac_cv_sizeof_pid_t=\${ac_cv_sizeof_pid_t=4}
ac_cv_sizeof_size_t=\${ac_cv_sizeof_size_t=4}
ac_cv_sizeof_ssize_t=\${ac_cv_sizeof_ssize_t=4}
ac_cv_func_setpgrp_void=\${ac_cv_func_setpgrp_void=no}
ac_cv_working_getnameinfo=\${ac_cv_working_getnameinfo=no}
ac_cv_working_getaddrinfo=\${ac_cv_working_getaddrinfo=no}
ac_cv_sctp=\${ac_cv_sctp=no}
EOF

(cd $APR; \
AUTOCONF=autoconf2.50 ./buildconf \
&& ./configure --host=arm-riscos-aof --prefix=$PREFIX -C \
&& mv include/apr.h include/apr.h.orig && \
sed 's/APR_HAS_MMAP.*/APR_HAS_MMAP 0/' < include/apr.h.orig > include/apr.h \
&& make clean && make && make install) || exit 1

(cd $APRUTIL; \
AUTOCONF=autoconf2.50 ./buildconf \
&& ./configure --host=arm-riscos-aof --prefix=$PREFIX \
--with-expat=$PREFIX --with-apr=../apr && \
make clean && \
touch uri/gen_uri_delims && \
touch uri/gen_uri_delims.lo && \
cp uri/uri_delims.h.pregen uri/uri_delims.h && \
touch uri/uri_delims.h && \
make && make install) || exit 1

exit 0

(cd $GETTEXT; \
./configure --with-included-gettext \
--host=arm-riscos-aof --prefix=$PREFIX \
&& make clean && make && make install) || exit 1
