#!/bin/sh

LIBXSLT=libxslt-1.1.15

if [ -n "$1" ]; then
 PREFIX=$1
else
 PREFIX=/home/riscos/env
fi

rm -rf $LIBXSLT
tar -xzf $LIBXSLT.tar.gz

export ac_cv_prog_cc_g=no
export lt_cv_prog_cc_can_build_shared=no
export lt_cv_prog_cc_pic_works=no
export ac_cv_working_getnameinfo=no
export ac_cv_func_getaddrinfo=no


(cd $LIBXSLT; \
ro-config --prefix=$PREFIX \
  --with-libxml-prefix=$PREFIX \
  --with-libxml-include-prefix=$PREFIX \
  --with-libxml-libs-prefix=$PREFIX \
  --without-crypto \
  --without-python \
&& make && make install) || exit 1

