#!/bin/sh

SABLOT=Sablot-1.0.1

if [ -n "$1" ]; then
 PREFIX=$1
else
 PREFIX=/home/riscos/cross/local
fi

rm -rf $SABLOT
tar -xzf $SABLOT.tar.gz

(cd $SABLOT; \
ro-config --prefix=$PREFIX \
--with-expat=$PREFIX \
&& make clean && make && make install) || exit 1

