#!/bin/sh

EXPAT=expat-1.95.4

if [ -n "$1" ]; then
 PREFIX=$1
else
 PREFIX=/home/riscos/cross/local
fi

rm -rf $EXPAT
tar -xzf $EXPAT.tar.gz

(cd $EXPAT; \
CFLAGS=-mpoke-function-name \
ro-config --prefix=$PREFIX \
&& make clean && make && make install) || exit 1

