#!/bin/sh

#DIRS=zlib-1.1.4 jpeg-6b libpng gd regex libiconv-1.8 expat-1.95.4 Sablot-0.95

OPENSSL=openssl-0.9.6g
NEON=neon-0.22.0
EXPAT=expat-1.95.4
ZLIB=zlib-1.1.4 
LIBPNG=libpng-1.2.0
REGEX=regex

PREFIX=/home/riscos/cross/local

#(cd $ZLIB; ./configure --prefix=$PREFIX \
#&& make clean && make && make install) || exit 1

#(cd $OPENSSL; ./Configure --prefix=$PREFIX -DNO_SYS_UN_H gcc) || exit 1

#(cd $EXPAT; \
#./configure --host=arm-riscos-aof --prefix=$PREFIX \
#&& make clean && make && make install) || exit 1

cat > $NEON/config.cache << EOF
ac_cv_prog_cc_g=\${ac_cv_prog_cc_g=no}
lt_cv_prog_cc_can_build_shared=\${lt_cv_prog_cc_can_build_shared=no}
lt_cv_prog_cc_pic_works=\${lt_cv_prog_cc_pic_works=no}
EOF

#(cd $NEON; \
#./configure --host=arm-riscos-aof -C --prefix=$PREFIX \
#--with-libs=$PREFIX --with-force-zlib --with-ssl \
#&& make clean && make && make install) || exit 1

#(cd $REGEX; \
#make clean && make && make install PREFIX=$PREFIX) || exit 1

(cd $LIBPNG; \
make clean && make PREFIX=$PREFIX && make install PREFIX=$PREFIX) || exit 1


