#!/bin/sh

#DIRS=zlib-1.1.4 jpeg-6b libpng gd regex libiconv-1.8 expat-1.95.4 Sablot-0.95
DIRS=zlib-1.1.4 

PREFIX=/home/riscos/cross/local
for dir in $DIRS; do
 (cd $dir; ./configure --prefix=$PREFIX)
done

for dir in $DIRS; do
 (cd $dir; make clean)
 (cd $dir; make)
 (cd $dir; make install)
done

exit
#openssl config
./Configure gcc --prefix=/home/riscos/cross/local
add -DNO_SYS_UN_H to CFLAGS in Makefile
Preprocess crypto/des/enc_read.c enc_writ.c read_pwd.c
and remove spurious #else
make
make install
