# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



SHELL = /bin/sh

srcdir = .
top_srcdir = ..

prefix = /home/riscos/cross/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/gettext
pkglibdir = $(libdir)/gettext
pkgincludedir = $(includedir)/gettext
top_builddir = ..

ACLOCAL = ${SHELL} /home/cross/libraries/gettext-0.11.5/missing --run aclocal
AUTOCONF = ${SHELL} /home/cross/libraries/gettext-0.11.5/missing --run autoconf
AUTOMAKE = ${SHELL} /home/cross/libraries/gettext-0.11.5/missing --run automake
AUTOHEADER = ${SHELL} /home/cross/libraries/gettext-0.11.5/missing --run autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = arm-riscos-aof
host_triplet = arm-riscos-aof
AMTAR = ${SHELL} /home/cross/libraries/gettext-0.11.5/missing --run tar
AS = as
AWK = mawk
BUILDJAVA = no
BUILDJAVAEXE = no
BUILD_INCLUDED_LIBINTL = yes
CATOBJEXT = .gmo
CC = gcc
CLASSPATH = 
CLASSPATH_SEPARATOR = :
CROSS_COMPILING = yes
CXX = c++
DATADIRNAME = share
DEPDIR = .deps
DLLTOOL = dlltool
DVIPS = /home/cross/libraries/gettext-0.11.5/missing dvips
ECHO = echo
EMACS = emacs
EXEEXT = 
GCC = yes
GCJ = none
GCJFLAGS = 
GENCAT = gencat
GLIBC21 = no
GMSGFMT = /usr/bin/msgfmt
HAVE_GCJ = 
HAVE_GCJ_C = 
HAVE_GCJ_IN_PATH = 
HAVE_GIJ = 
HAVE_GIJ_IN_PATH = 
HAVE_JAVA = 
HAVE_JAVAC = 
HAVE_JAVAC_IN_PATH = 
HAVE_JAVA_IN_PATH = 
HAVE_JIKES = 
HAVE_JIKES_IN_PATH = 
HAVE_JRE = 
HAVE_JRE_IN_PATH = 
HAVE_JVIEW = 
HAVE_JVIEW_IN_PATH = 
HAVE_LIB = @HAVE_LIB@
HAVE__BOOL = 0
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
INSTOBJEXT = .mo
INTLBISON = bison
INTLLIBS = ${top_builddir}/intl/libintl.la 
INTLOBJS = $(GETTOBJS)
INTL_LIBTOOL_SUFFIX_PREFIX = l
JAVA = 
JAVAC = 
LD = /home/riscos/cross-7.7.2002/bin/arm-riscos-aof/2_95_4/ld
LEX = flex
LEX_OUTPUT_ROOT = lex.yy
LIB = @LIB@
LIBEXPAT = /home/riscos/cross/local/lib/libexpat.a
LIBICONV = 
LIBINTL = ${top_builddir}/intl/libintl.la 
LIBOBJS =  vasprintf.o getline.o pfnmatch.o mkdtemp.o
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
LTALLOCA = 
LTLIB = @LTLIB@
LTLIBEXPAT = -L/home/riscos/cross/local/lib -lexpat
LTLIBICONV = 
LTLIBINTL = ${top_builddir}/intl/libintl.la 
LTLIBOBJS =  vasprintf.lo getline.lo pfnmatch.lo mkdtemp.lo
MKINSTALLDIRS = ./mkinstalldirs
OBJDUMP = objdump
OBJEXT = o
PACKAGE = gettext
PERL = /usr/bin/perl
POSUB = po
RANLIB = ranlib
STDBOOL_H = stdbool.h
STRIP = strip
TESTJAVA = no
TEXI2PDF = /home/cross/libraries/gettext-0.11.5/missing texi2pdf
USE_INCLUDED_LIBINTL = yes
USE_NLS = yes
VERSION = 0.11.5
YACC = bison -y
aclocaldir = ${datadir}/aclocal
am__include = include
am__quote = 
install_sh = /home/cross/libraries/gettext-0.11.5/install-sh
lispdir = ${datadir}/emacs/site-lisp
with_gnu_ld = no

JAR = 

AUTOMAKE_OPTIONS = 1.2 gnits

RM = rm -f

jardir = $(datadir)/gettext
docdir = $(prefix)/doc/gettext
htmldir = $(docdir)
JAVACOMP = $(SHELL) ../lib/javacomp.sh
JAVADOC1 = test ! -d /usr/lib/jdk1.1.8 || env PATH=/usr/lib/jdk1.1.8/bin:$$PATH javadoc
JAVADOC2 = test ! -d /usr/lib/jdk1.3.1 || env PATH=/usr/lib/jdk1.3.1/bin:$$PATH javadoc

EXTRA_DIST = gnu/gettext/GettextResource.java $(JAVADOC1_FILES) $(JAVADOC2_FILES)

CLEANFILES = libintl.jar gnu/gettext/*.class

JAVADOC1_FILES = \
  javadoc1/packages.html javadoc1/tree.html javadoc1/AllNames.html \
  javadoc1/gnu.gettext.GettextResource.html \
  javadoc1/images/blue-ball-small.gif javadoc1/images/blue-ball.gif \
  javadoc1/images/class-index.gif \
  javadoc1/images/constructor-index.gif \
  javadoc1/images/constructors.gif \
  javadoc1/images/cyan-ball-small.gif javadoc1/images/cyan-ball.gif \
  javadoc1/images/error-index.gif \
  javadoc1/images/exception-index.gif \
  javadoc1/images/green-ball-small.gif javadoc1/images/green-ball.gif \
  javadoc1/images/interface-index.gif \
  javadoc1/images/magenta-ball-small.gif javadoc1/images/magenta-ball.gif \
  javadoc1/images/method-index.gif \
  javadoc1/images/methods.gif \
  javadoc1/images/package-index.gif \
  javadoc1/images/red-ball-small.gif javadoc1/images/red-ball.gif \
  javadoc1/images/variable-index.gif \
  javadoc1/images/variables.gif \
  javadoc1/images/yellow-ball-small.gif javadoc1/images/yellow-ball.gif


JAVADOC2_FILES = \
  javadoc2/index.html \
  javadoc2/allclasses-frame.html \
  javadoc2/overview-tree.html \
  javadoc2/deprecated-list.html \
  javadoc2/serialized-form.html \
  javadoc2/index-all.html \
  javadoc2/help-doc.html \
  javadoc2/packages.html \
  javadoc2/package-list \
  javadoc2/stylesheet.css \
  javadoc2/gnu/gettext/package-summary.html \
  javadoc2/gnu/gettext/package-tree.html \
  javadoc2/gnu/gettext/package-frame.html \
  javadoc2/gnu/gettext/GettextResource.html

subdir = intl-java
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
DIST_SOURCES =
DIST_COMMON = ChangeLog Makefile.am Makefile.in
all: all-am

.SUFFIXES:

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnits  intl-java/Makefile
Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	  CONFIG_HEADERS= CONFIG_LINKS= \
	  CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status
uninstall-info-am:
tags: TAGS
TAGS:


DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = ..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	$(mkinstalldirs) $(distdir)/gnu/gettext $(distdir)/javadoc1 $(distdir)/javadoc1/images $(distdir)/javadoc2 $(distdir)/javadoc2/gnu/gettext
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    $(mkinstalldirs) "$(distdir)/$$dir"; \
	  fi; \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile all-local

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libtool mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-generic distclean-libtool

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am: install-data-local

install-exec-am:

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-generic mostlyclean-libtool

uninstall-am: uninstall-info-am uninstall-local

.PHONY: all all-am all-local check check-am clean clean-generic \
	clean-libtool distclean distclean-generic distclean-libtool \
	distdir dvi dvi-am info info-am install install-am install-data \
	install-data-am install-data-local install-exec install-exec-am \
	install-info install-info-am install-man install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-generic \
	mostlyclean-libtool uninstall uninstall-am uninstall-info-am \
	uninstall-local


all-local: all-classes all-javadoc1 all-javadoc2
install-data-local: install-classes install-javadoc1 install-javadoc2
installdirs-local: installdirs-classes installdirs-javadoc1 installdirs-javadoc2
uninstall-local: uninstall-classes uninstall-javadoc1 uninstall-javadoc2

# Special rules for Java compilation.

all-classes: all-classes-no
all-classes-no:
all-classes-yes: libintl.jar

gnu/gettext/GettextResource.class: $(srcdir)/gnu/gettext/GettextResource.java
	$(JAVACOMP) -d . $(srcdir)/gnu/gettext/GettextResource.java

libintl.jar: gnu/gettext/GettextResource.class
	$(JAR) cf $@ gnu/gettext/GettextResource*.class

install-classes: install-classes-no
install-classes-no:
	$(mkinstalldirs) $(DESTDIR)$(jardir)
install-classes-yes: all-classes-yes
	$(mkinstalldirs) $(DESTDIR)$(jardir)
	$(INSTALL_DATA) libintl.jar $(DESTDIR)$(jardir)/libintl.jar

installdirs-classes:
	$(mkinstalldirs) $(DESTDIR)$(jardir)

uninstall-classes:
	$(RM) $(DESTDIR)$(jardir)/libintl.jar

# Special rules for Javadoc (JDK 1.1) documentation.

all-javadoc1: $(srcdir)/javadoc1/tree.html

$(srcdir)/javadoc1/tree.html: $(srcdir)/gnu/gettext/GettextResource.java
	cd $(srcdir) && $(JAVADOC1) -d javadoc1 gnu/gettext/*.java

install-javadoc1: all-javadoc1
	$(mkinstalldirs) $(DESTDIR)$(htmldir)/javadoc1
	$(mkinstalldirs) $(DESTDIR)$(htmldir)/javadoc1/images
	@for f in $(JAVADOC1_FILES); do \
	  echo "$(INSTALL_DATA) $(srcdir)/$$f $(DESTDIR)$(htmldir)/$$f"; \
	  $(INSTALL_DATA) $(srcdir)/$$f $(DESTDIR)$(htmldir)/$$f; \
	done

installdirs-javadoc1:
	$(mkinstalldirs) $(DESTDIR)$(htmldir)/javadoc1
	$(mkinstalldirs) $(DESTDIR)$(htmldir)/javadoc1/images

uninstall-javadoc1:
	@for f in $(JAVADOC1_FILES); do \
	  echo "$(RM) $(DESTDIR)$(htmldir)/$$f"; \
	  $(RM) $(DESTDIR)$(htmldir)/$$f; \
	done

# Special rules for Javadoc (JDK 1.2) documentation.

all-javadoc2: $(srcdir)/javadoc2/index.html

$(srcdir)/javadoc2/index.html: $(srcdir)/gnu/gettext/GettextResource.java
	cd $(srcdir) && $(JAVADOC2) -d javadoc2 gnu/gettext/*.java

install-javadoc2: all-javadoc2
	$(mkinstalldirs) $(DESTDIR)$(htmldir)/javadoc2
	$(mkinstalldirs) $(DESTDIR)$(htmldir)/javadoc2/gnu/gettext
	@for f in $(JAVADOC2_FILES); do \
	  echo "$(INSTALL_DATA) $(srcdir)/$$f $(DESTDIR)$(htmldir)/$$f"; \
	  $(INSTALL_DATA) $(srcdir)/$$f $(DESTDIR)$(htmldir)/$$f; \
	done

installdirs-javadoc2:
	$(mkinstalldirs) $(DESTDIR)$(htmldir)/javadoc2
	$(mkinstalldirs) $(DESTDIR)$(htmldir)/javadoc2/gnu/gettext

uninstall-javadoc2:
	@for f in $(JAVADOC2_FILES); do \
	  echo "$(RM) $(DESTDIR)$(htmldir)/$$f"; \
	  $(RM) $(DESTDIR)$(htmldir)/$$f; \
	done

# One more automake bug.
installdirs: installdirs-local
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
