# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



SHELL = /bin/sh

srcdir = .
top_srcdir = ..

prefix = /home/riscos/cross/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/gettext
pkglibdir = $(libdir)/gettext
pkgincludedir = $(includedir)/gettext
top_builddir = ..

ACLOCAL = ${SHELL} /home/cross/libraries/gettext-0.11.5/missing --run aclocal
AUTOCONF = ${SHELL} /home/cross/libraries/gettext-0.11.5/missing --run autoconf
AUTOMAKE = ${SHELL} /home/cross/libraries/gettext-0.11.5/missing --run automake
AUTOHEADER = ${SHELL} /home/cross/libraries/gettext-0.11.5/missing --run autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = arm-riscos-aof
host_triplet = arm-riscos-aof
AMTAR = ${SHELL} /home/cross/libraries/gettext-0.11.5/missing --run tar
AS = as
AWK = mawk
BUILDJAVA = no
BUILDJAVAEXE = no
BUILD_INCLUDED_LIBINTL = yes
CATOBJEXT = .gmo
CC = gcc
CLASSPATH = 
CLASSPATH_SEPARATOR = :
CROSS_COMPILING = yes
CXX = c++
DATADIRNAME = share
DEPDIR = .deps
DLLTOOL = dlltool
DVIPS = /home/cross/libraries/gettext-0.11.5/missing dvips
ECHO = echo
EMACS = emacs
EXEEXT = 
GCC = yes
GCJ = none
GCJFLAGS = 
GENCAT = gencat
GLIBC21 = no
GMSGFMT = /usr/bin/msgfmt
HAVE_GCJ = 
HAVE_GCJ_C = 
HAVE_GCJ_IN_PATH = 
HAVE_GIJ = 
HAVE_GIJ_IN_PATH = 
HAVE_JAVA = 
HAVE_JAVAC = 
HAVE_JAVAC_IN_PATH = 
HAVE_JAVA_IN_PATH = 
HAVE_JIKES = 
HAVE_JIKES_IN_PATH = 
HAVE_JRE = 
HAVE_JRE_IN_PATH = 
HAVE_JVIEW = 
HAVE_JVIEW_IN_PATH = 
HAVE_LIB = @HAVE_LIB@
HAVE__BOOL = 0
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
INSTOBJEXT = .mo
INTLBISON = bison
INTLLIBS = ${top_builddir}/intl/libintl.la 
INTLOBJS = $(GETTOBJS)
INTL_LIBTOOL_SUFFIX_PREFIX = l
JAR = 
JAVA = 
JAVAC = 
LD = /home/riscos/cross-7.7.2002/bin/arm-riscos-aof/2_95_4/ld
LEX = flex
LEX_OUTPUT_ROOT = lex.yy
LIB = @LIB@
LIBEXPAT = /home/riscos/cross/local/lib/libexpat.a
LIBICONV = 
LIBINTL = ${top_builddir}/intl/libintl.la 
LIBOBJS =  vasprintf.o getline.o pfnmatch.o mkdtemp.o
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
LTALLOCA = 
LTLIB = @LTLIB@
LTLIBEXPAT = -L/home/riscos/cross/local/lib -lexpat
LTLIBICONV = 
LTLIBINTL = ${top_builddir}/intl/libintl.la 
LTLIBOBJS =  vasprintf.lo getline.lo pfnmatch.lo mkdtemp.lo
MKINSTALLDIRS = ./mkinstalldirs
OBJDUMP = objdump
OBJEXT = o
PACKAGE = gettext
PERL = /usr/bin/perl
POSUB = po
RANLIB = ranlib
STDBOOL_H = stdbool.h
STRIP = strip
TESTJAVA = no
TEXI2PDF = /home/cross/libraries/gettext-0.11.5/missing texi2pdf
USE_INCLUDED_LIBINTL = yes
USE_NLS = yes
VERSION = 0.11.5
YACC = bison -y
aclocaldir = ${datadir}/aclocal
am__include = include
am__quote = 
install_sh = /home/cross/libraries/gettext-0.11.5/install-sh
lispdir = ${datadir}/emacs/site-lisp
with_gnu_ld = no

AUTOMAKE_OPTIONS = 1.5 gnits no-dependencies

RM = rm -f

lib_LTLIBRARIES = libgettextlib.la


# Sources that are compiled on all platforms.
libgettextlib_la_SOURCES = \
  argmatch.h argmatch.c \
  backupfile.h backupfile.c addext.c \
  basename.h basename.c \
  binary-io.h \
  c-ctype.h c-ctype.c \
  copy-file.h copy-file.c \
  error.h error.c \
  execute.h execute.c \
  exit.h \
  findprog.h findprog.c \
  fstrcmp.h fstrcmp.c \
  full-write.h full-write.c \
  gcd.h gcd.c \
  getopt.h getopt.c getopt1.c \
  hash.h hash.c \
  javacomp.h javacomp.c \
  javaexec.h javaexec.c \
  linebreak.h linebreak.c lbrkprop.h utf8-ucs4.h utf16-ucs4.h \
  localcharset.c \
  mbswidth.h mbswidth.c \
  minmax.h \
  obstack.h obstack.c \
  pathmax.h \
  pathname.h concatpath.c \
  pipe.h pipe-bidi.c pipe-in.c pipe-out.c \
  progname.h progname.c \
  safe-read.h safe-read.c \
  sh-quote.h sh-quote.c \
  stpncpy.h stpncpy.c \
  strtoul.c \
  tmpdir.h tmpdir.c \
  ucs4-utf8.h ucs4-utf16.h \
  wait-process.h wait-process.c \
  xerror.h xerror.c \
  xmalloc.h xmalloc.c xstrdup.c \
  xsetenv.h xsetenv.c



# Sources that are compiled only on platforms that lack the functions.
LIBADD_SOURCE = \
  liballoca.h alloca.c \
  getline.h getline.c \
  memset.c \
  mkdtemp.h mkdtemp.c \
  pfnmatch.h pfnmatch.c \
  setenv.h setenv.c unsetenv.c \
  libstdarg.h \
  stpcpy.h stpcpy.c \
  strcase.h strcasecmp.c strncasecmp.c \
  strcspn.c \
  strpbrk.h strpbrk.c \
  strstr.h strstr.c \
  strtol.c \
  vasprintf.h vasprintf.c



# Unused sources.
UNUSED_SOURCE = \
  memmove.c \
  xgetcwd.h xgetcwd.c



# How to build libgettextlib.la.
libgettextlib_la_LIBADD =   vasprintf.lo getline.lo pfnmatch.lo mkdtemp.lo

# Need ${top_builddir}/intl/libintl.la  because many source files use gettext().
# Need  because linebreak.c uses iconv().
libgettextlib_la_LDFLAGS = \
  -release 0.11.5 \
  ${top_builddir}/intl/libintl.la   -lc -no-undefined



# Extra files to be installed.
gettextsrcdir = $(datadir)/gettext
gettextsrc_DATA = gettext.h


# List of files to be distributed.
noinst_HEADERS = gettext.h

EXTRA_DIST = classpath.c config.charset ref-add.sin ref-del.sin \
$(LIBADD_SOURCE) $(UNUSED_SOURCE) \
stdbool.h.in \
gen-lbrkprop.c 3level.h Combining.txt


DEFS = -DLIBDIR=\"$(libdir)\" -DEXEEXT=\"$(EXEEXT)\" -DHAVE_CONFIG_H
INCLUDES = -I. -I$(srcdir) -I.. -I../intl -I$(top_srcdir)/intl

DISTCLEANFILES = fnmatch.h
MOSTLYCLEANFILES = stdbool.h

charset_alias = $(DESTDIR)$(libdir)/charset.alias
charset_tmp = $(DESTDIR)$(libdir)/charset.tmp

SUFFIXES = .sed .sin

CLEANFILES = charset.alias ref-add.sed ref-del.sed
subdir = lib
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES = javacomp.sh javaexec.sh
LTLIBRARIES = $(lib_LTLIBRARIES)

libgettextlib_la_DEPENDENCIES =   vasprintf.lo getline.lo pfnmatch.lo mkdtemp.lo
am_libgettextlib_la_OBJECTS = argmatch.lo backupfile.lo addext.lo \
	basename.lo c-ctype.lo copy-file.lo error.lo execute.lo \
	findprog.lo fstrcmp.lo full-write.lo gcd.lo getopt.lo \
	getopt1.lo hash.lo javacomp.lo javaexec.lo linebreak.lo \
	localcharset.lo mbswidth.lo obstack.lo concatpath.lo \
	pipe-bidi.lo pipe-in.lo pipe-out.lo progname.lo safe-read.lo \
	sh-quote.lo stpncpy.lo strtoul.lo tmpdir.lo wait-process.lo \
	xerror.lo xmalloc.lo xstrdup.lo xsetenv.lo
libgettextlib_la_OBJECTS = $(am_libgettextlib_la_OBJECTS)
DEFAULT_INCLUDES =  -I. -I$(srcdir) -I$(top_builddir)
CPPFLAGS = -I/home/riscos/cross/local/include
LDFLAGS = 
LIBS = 
depcomp =
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) \
	$(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
CFLAGS = -D_INTL_REDIRECT_MACROS
DIST_SOURCES = $(libgettextlib_la_SOURCES)
DATA = $(gettextsrc_DATA)

HEADERS = $(noinst_HEADERS)

DIST_COMMON = $(noinst_HEADERS) ChangeLog Makefile.am Makefile.in \
	alloca.c getline.c javacomp.sh.in javaexec.sh.in memset.c \
	mkdtemp.c pfnmatch.c setenv.c stpcpy.c strcasecmp.c strcspn.c \
	strncasecmp.c strpbrk.c strstr.c unsetenv.c vasprintf.c
SOURCES = $(libgettextlib_la_SOURCES)

all: all-am

.SUFFIXES:
.SUFFIXES: .sed .sin .c .lo .o .obj

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnits  lib/Makefile
Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	  CONFIG_HEADERS= CONFIG_LINKS= \
	  CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status
javacomp.sh: $(top_builddir)/config.status javacomp.sh.in
	cd $(top_builddir) && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= CONFIG_LINKS= $(SHELL) ./config.status
javaexec.sh: $(top_builddir)/config.status javaexec.sh.in
	cd $(top_builddir) && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= CONFIG_LINKS= $(SHELL) ./config.status
install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(libdir)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(LIBTOOL) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$p $(DESTDIR)$(libdir)/$$p"; \
	    $(LIBTOOL) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$p $(DESTDIR)$(libdir)/$$p; \
	  else :; fi; \
	done

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  echo " $(LIBTOOL) --mode=uninstall rm -f $(DESTDIR)$(libdir)/$$p"; \
	  $(LIBTOOL) --mode=uninstall rm -f $(DESTDIR)$(libdir)/$$p; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
libgettextlib.la: $(libgettextlib_la_OBJECTS) $(libgettextlib_la_DEPENDENCIES) 
	$(LINK) -rpath $(libdir) $(libgettextlib_la_LDFLAGS) $(libgettextlib_la_OBJECTS) $(libgettextlib_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

.c.o:
	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.c.lo:
	$(LTCOMPILE) -c -o $@ $<
uninstall-info-am:
install-gettextsrcDATA: $(gettextsrc_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(gettextsrcdir)
	@list='$(gettextsrc_DATA)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f="`echo $$p | sed -e 's|^.*/||'`"; \
	  echo " $(INSTALL_DATA) $$d$$p $(DESTDIR)$(gettextsrcdir)/$$f"; \
	  $(INSTALL_DATA) $$d$$p $(DESTDIR)$(gettextsrcdir)/$$f; \
	done

uninstall-gettextsrcDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(gettextsrc_DATA)'; for p in $$list; do \
	  f="`echo $$p | sed -e 's|^.*/||'`"; \
	  echo " rm -f $(DESTDIR)$(gettextsrcdir)/$$f"; \
	  rm -f $(DESTDIR)$(gettextsrcdir)/$$f; \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH

DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = ..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    $(mkinstalldirs) "$(distdir)/$$dir"; \
	  fi; \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES) $(DATA) $(HEADERS) all-local

installdirs:
	$(mkinstalldirs) $(DESTDIR)$(libdir) $(DESTDIR)$(gettextsrcdir)

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:
	-test -z "$(MOSTLYCLEANFILES)" || rm -f $(MOSTLYCLEANFILES)

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*
	-test -z "$(DISTCLEANFILES)" || rm -f $(DISTCLEANFILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libLTLIBRARIES clean-libtool \
	mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-compile distclean-generic \
	distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am: install-gettextsrcDATA

install-exec-am: install-exec-local install-libLTLIBRARIES

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

uninstall-am: uninstall-gettextsrcDATA uninstall-info-am \
	uninstall-libLTLIBRARIES uninstall-local

.PHONY: GTAGS all all-am all-local check check-am clean clean-generic \
	clean-libLTLIBRARIES clean-libtool distclean distclean-compile \
	distclean-generic distclean-libtool distclean-tags distdir dvi \
	dvi-am info info-am install install-am install-data \
	install-data-am install-exec install-exec-am install-exec-local \
	install-gettextsrcDATA install-info install-info-am \
	install-libLTLIBRARIES install-man install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool tags uninstall \
	uninstall-am uninstall-gettextsrcDATA uninstall-info-am \
	uninstall-libLTLIBRARIES uninstall-local


# No need to install libgettextlib.a.
install-exec-am: install-exec-clean
install-exec-clean:
	$(RM) $(DESTDIR)$(libdir)/libgettextlib.a

all-local c-ctype.lo execute.lo javacomp.lo javaexec.lo pipe-bidi.lo pipe-in.lo pipe-out.lo progname.lo tmpdir.lo wait-process.lo xerror.lo: stdbool.h
stdbool.h: stdbool.h.in
	sed -e 's/@''HAVE__BOOL''@/0/g' < $(srcdir)/stdbool.h.in > stdbool.h

# The following is needed in order to install a simple file in $(libdir)
# which is shared with other installed packages. We use a list of referencing
# packages so that "make uninstall" will remove the file if and only if it
# is not used by another installed package.
# On systems with glibc-2.1 or newer, the file is redundant, therefore we
# avoid installing it.

all-local: charset.alias ref-add.sed ref-del.sed
install-exec-local: all-local
	$(mkinstalldirs) $(DESTDIR)$(libdir)
	if test -f $(charset_alias); then \
	  sed -f ref-add.sed $(charset_alias) > $(charset_tmp) ; \
	  $(INSTALL_DATA) $(charset_tmp) $(charset_alias) ; \
	  rm -f $(charset_tmp) ; \
	else \
	  if test no = no; then \
	    sed -f ref-add.sed charset.alias > $(charset_tmp) ; \
	    $(INSTALL_DATA) $(charset_tmp) $(charset_alias) ; \
	    rm -f $(charset_tmp) ; \
	  fi ; \
	fi

uninstall-local: all-local
	if test -f $(charset_alias); then \
	  sed -f ref-del.sed $(charset_alias) > $(charset_tmp); \
	  if grep '^# Packages using this file: $$' $(charset_tmp) \
	      > /dev/null; then \
	    rm -f $(charset_alias); \
	  else \
	    $(INSTALL_DATA) $(charset_tmp) $(charset_alias); \
	  fi; \
	  rm -f $(charset_tmp); \
	fi

charset.alias: config.charset
	$(SHELL) $(srcdir)/config.charset 'arm-riscos-aof' > t-$@
	mv t-$@ $@
.sin.sed:
	sed -e '/^#/d' -e 's/@''PACKAGE''@/gettext/g' $< > t-$@
	mv t-$@ $@
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
