; Generated by gcc 2.95.4 20010319 (prerelease) [gccsdk 20020112] for ARM/RISC OS
__r0	RN	0
__r1	RN	1
__r2	RN	2
__r3	RN	3
__r4	RN	4
__r5	RN	5
__r6	RN	6
__r7	RN	7
__r8	RN	8
__r9	RN	9
__r10	RN	10
__r11	RN	11
__r12	RN	12
__r13	RN	13
__r14	RN	14
__r15	RN	15
__a1	RN	0
__a2	RN	1
__a3	RN	2
__a4	RN	3
__v1	RN	4
__v2	RN	5
__v3	RN	6
__v4	RN	7
__v5	RN	8
__v6	RN	9
__sl	RN	10
__fp	RN	11
__ip	RN	12
__sp	RN	13
__lr	RN	14
__pc	RN	15
__f0	FN	0
__f1	FN	1
__f2	FN	2
__f3	FN	3
__f4	FN	4
__f5	FN	5
__f6	FN	6
__f7	FN	7
	AREA |C$$code1|, CODE, READONLY
|gcc2_compiled.|
	EXPORT	|xmalloc_exit_failure|
	AREA |C$$data1|, DATA
	ALIGN
|xmalloc_exit_failure|
	DCD	1
	AREA |C$$code2|, CODE, READONLY
	ALIGN
|LC..0|
	DCB &6d, &65, &6d, &6f
	DCB &72, &79, &20, &65
	DCB &78, &68, &61, &75
	DCB &73, &74, &65, &64
	DCB &00
	ALIGN
|fixup_null_alloc|
	KEEP |fixup_null_alloc|
	; args = 0, pretend = 0, frame = 0, alloca = 0
	; frame_needed = 1, anonymous_args = 0, regs_live[14] = 0
	; nonlocal_label = 0, nonlocal_goto = 0, clobbers lr = 1
	mov	__ip, __sp
	stmfd	__sp!, {__v1, __v2, __fp, __ip, __lr, __pc}
	sub	__fp, __ip, #4
	cmp	__sp, __sl
	IMPORT	|__rt_stkovf_split_small|
	bllt	|__rt_stkovf_split_small|
	mov	__v2, #0
	cmp	__a1, __v2
	moveq	__a1, #1
	bleq	|malloc|
	moveq	__v2, __a1
|L..3|
	cmp	__v2, #0
	bne	|L..4|
	ldr	__ip, |L..5|
	ldr	__a1, |L..5|+4
	ldr	__v1, [__ip, #0]
	bl	|libintl_gettext|
	mov	__a3, __a1
	mov	__a2, __v2
	mov	__a1, __v1
	bl	|error|
|L..4|
	mov	__a1, __v2
	ldmea	__fp, {__v1, __v2, __fp, __sp, __pc}^
|L..6|
	ALIGN
|L..5|
	DCD	|xmalloc_exit_failure|
	DCD	|LC..0|
	ALIGN
	EXPORT	|xmalloc|
|xmalloc|
	; args = 0, pretend = 0, frame = 0, alloca = 0
	; frame_needed = 1, anonymous_args = 0, regs_live[14] = 0
	; nonlocal_label = 0, nonlocal_goto = 0, clobbers lr = 1
	mov	__ip, __sp
	stmfd	__sp!, {__v1, __fp, __ip, __lr, __pc}
	sub	__fp, __ip, #4
	cmp	__sp, __sl
	IMPORT	|__rt_stkovf_split_small|
	bllt	|__rt_stkovf_split_small|
	mov	__v1, __a1
	bl	|malloc|
	cmp	__a1, #0
	ldmneea	__fp, {__v1, __fp, __sp, __pc}^
	mov	__a1, __v1
	ldmea	__fp, {__v1, __fp, __sp, __lr}
	b	|fixup_null_alloc|
	ALIGN
	EXPORT	|xcalloc|
|xcalloc|
	; args = 0, pretend = 0, frame = 0, alloca = 0
	; frame_needed = 1, anonymous_args = 0, regs_live[14] = 0
	; nonlocal_label = 0, nonlocal_goto = 0, clobbers lr = 1
	mov	__ip, __sp
	stmfd	__sp!, {__v1, __fp, __ip, __lr, __pc}
	sub	__fp, __ip, #4
	cmp	__sp, __sl
	IMPORT	|__rt_stkovf_split_small|
	bllt	|__rt_stkovf_split_small|
	mov	__v1, __a1
	bl	|calloc|
	cmp	__a1, #0
	ldmneea	__fp, {__v1, __fp, __sp, __pc}^
	mov	__a1, __v1
	ldmea	__fp, {__v1, __fp, __sp, __lr}
	b	|fixup_null_alloc|
	ALIGN
	EXPORT	|xrealloc|
|xrealloc|
	; args = 0, pretend = 0, frame = 0, alloca = 0
	; frame_needed = 1, anonymous_args = 0, regs_live[14] = 0
	; nonlocal_label = 0, nonlocal_goto = 0, clobbers lr = 1
	mov	__ip, __sp
	stmfd	__sp!, {__v1, __fp, __ip, __lr, __pc}
	sub	__fp, __ip, #4
	cmp	__sp, __sl
	IMPORT	|__rt_stkovf_split_small|
	bllt	|__rt_stkovf_split_small|
	cmp	__a1, #0
	mov	__v1, __a2
	bne	|L..12|
	mov	__a1, __v1
	ldmea	__fp, {__v1, __fp, __sp, __lr}
	b	|xmalloc|
|L..12|
	mov	__a2, __v1
	bl	|realloc|
	cmp	__a1, #0
	ldmneea	__fp, {__v1, __fp, __sp, __pc}^
	mov	__a1, __v1
	ldmea	__fp, {__v1, __fp, __sp, __lr}
	b	|fixup_null_alloc|
	IMPORT	|realloc|
	IMPORT	|calloc|
	IMPORT	|libintl_gettext|
	IMPORT	|error|
	IMPORT	|malloc|
	END
