/* ========= begin header generated by ./mkh ========= */
#ifdef __cplusplus
extern "C" {
#endif

/* === engine.ih === */

#ifdef __cplusplus
}
#endif
/* ========= end header generated by ./mkh ========= */
