; Generated by gcc 2.95.4 20010319 (prerelease) [gccsdk 20020112] for ARM/RISC OS
__r0	RN	0
__r1	RN	1
__r2	RN	2
__r3	RN	3
__r4	RN	4
__r5	RN	5
__r6	RN	6
__r7	RN	7
__r8	RN	8
__r9	RN	9
__r10	RN	10
__r11	RN	11
__r12	RN	12
__r13	RN	13
__r14	RN	14
__r15	RN	15
__a1	RN	0
__a2	RN	1
__a3	RN	2
__a4	RN	3
__v1	RN	4
__v2	RN	5
__v3	RN	6
__v4	RN	7
__v5	RN	8
__v6	RN	9
__sl	RN	10
__fp	RN	11
__ip	RN	12
__sp	RN	13
__lr	RN	14
__pc	RN	15
__f0	FN	0
__f1	FN	1
__f2	FN	2
__f3	FN	3
__f4	FN	4
__f5	FN	5
__f6	FN	6
__f7	FN	7
	AREA |C$$code1|, CODE, READONLY
|gcc2_compiled.|
	ALIGN
|LC..0|
	DCB &67, &64, &2d, &70
	DCB &6e, &67, &3a, &20
	DCB &20, &66, &61, &74
	DCB &61, &6c, &20, &6c
	DCB &69, &62, &70, &6e
	DCB &67, &20, &65, &72
	DCB &72, &6f, &72, &3a
	DCB &20, &25, &73, &0a
	DCB &00
	ALIGN
|LC..1|
	DCB &67, &64, &2d, &70
	DCB &6e, &67, &3a, &20
	DCB &20, &45, &58, &54
	DCB &52, &45, &4d, &45
	DCB &4c, &59, &20, &66
	DCB &61, &74, &61, &6c
	DCB &20, &65, &72, &72
	DCB &6f, &72, &3a, &20
	DCB &6a, &6d, &70, &62
	DCB &75, &66, &20, &75
	DCB &6e, &72, &65, &63
	DCB &6f, &76, &65, &72
	DCB &61, &62, &6c, &65
	DCB &3b, &20, &74, &65
	DCB &72, &6d, &69, &6e
	DCB &61, &74, &69, &6e
	DCB &67, &2e, &0a, &00
	ALIGN
	DCB &67, &64, &50, &6e
	DCB &67, &45, &72, &72
	DCB &6f, &72, &48, &61
	DCB &6e, &64, &6c, &65
	DCB &72, &00
	ALIGN
	DCD	-16777196
|gdPngErrorHandler|
	KEEP |gdPngErrorHandler|
	; args = 0, pretend = 0, frame = 12, alloca = 0
	; frame_needed = 1, anonymous_args = 0, regs_live[14] = 0
	; nonlocal_label = 0, nonlocal_goto = 0, clobbers lr = 1
	mov	__ip, __sp
	stmfd	__sp!, {__v6, __fp, __ip, __lr, __pc}
	sub	__fp, __ip, #4
	cmp	__sp, __sl
	IMPORT	|__rt_stkovf_split_small|
	bllt	|__rt_stkovf_split_small|
	sub	__sp, __sp, #12
	mov	__v6, __sp
	str	__a1, [__v6, #0]
	str	__a2, [__v6, #4]
	ldr	__ip, |L..4|
	ldr	__a1, [__ip, #0]
	ldr	__a2, |L..4|+4
	ldr	__a3, [__v6, #4]
	bl	|fprintf|
	ldr	__ip, |L..4|
	ldr	__a1, [__ip, #0]
	bl	|fflush|
	ldr	__a1, [__v6, #0]
	bl	|png_get_error_ptr|
	str	__a1, [__v6, #8]
	ldr	__ip, [__v6, #8]
	cmp	__ip, #0
	bne	|L..3|
	ldr	__ip, |L..4|
	ldr	__a1, [__ip, #0]
	ldr	__a2, |L..4|+8
	bl	|fprintf|
	ldr	__ip, |L..4|
	ldr	__a1, [__ip, #0]
	bl	|fflush|
	mov	__a1, #99
	bl	|exit|
|L..3|
	ldr	__a1, [__v6, #8]
	mov	__a2, #1
	bl	|___arm_alloca_longjmp|
|L..5|
	ALIGN
|L..4|
	DCD	|__stderr|
	DCD	|LC..0|
	DCD	|LC..1|
|L..2|
	ldmea	__fp, {__v6, __fp, __sp, __pc}^
	ALIGN
	DCB &67, &64, &50, &6e
	DCB &67, &52, &65, &61
	DCB &64, &44, &61, &74
	DCB &61, &00
	ALIGN
	DCD	-16777200
|gdPngReadData|
	KEEP |gdPngReadData|
	; args = 0, pretend = 0, frame = 12, alloca = 0
	; frame_needed = 1, anonymous_args = 0, regs_live[14] = 0
	; nonlocal_label = 0, nonlocal_goto = 0, clobbers lr = 1
	mov	__ip, __sp
	stmfd	__sp!, {__v6, __fp, __ip, __lr, __pc}
	sub	__fp, __ip, #4
	cmp	__sp, __sl
	IMPORT	|__rt_stkovf_split_small|
	bllt	|__rt_stkovf_split_small|
	sub	__sp, __sp, #12
	mov	__v6, __sp
	str	__a1, [__v6, #0]
	str	__a2, [__v6, #4]
	str	__a3, [__v6, #8]
	ldr	__a1, [__v6, #0]
	bl	|png_get_io_ptr|
	mov	__ip, __a1
	ldr	__a1, [__v6, #4]
	ldr	__a2, [__v6, #8]
	mov	__a3, __ip
	bl	|gdGetBuf|
|L..6|
	ldmea	__fp, {__v6, __fp, __sp, __pc}^
	ALIGN
	DCB &67, &64, &50, &6e
	DCB &67, &57, &72, &69
	DCB &74, &65, &44, &61
	DCB &74, &61, &00
	ALIGN
	DCD	-16777200
|gdPngWriteData|
	KEEP |gdPngWriteData|
	; args = 0, pretend = 0, frame = 12, alloca = 0
	; frame_needed = 1, anonymous_args = 0, regs_live[14] = 0
	; nonlocal_label = 0, nonlocal_goto = 0, clobbers lr = 1
	mov	__ip, __sp
	stmfd	__sp!, {__v6, __fp, __ip, __lr, __pc}
	sub	__fp, __ip, #4
	cmp	__sp, __sl
	IMPORT	|__rt_stkovf_split_small|
	bllt	|__rt_stkovf_split_small|
	sub	__sp, __sp, #12
	mov	__v6, __sp
	str	__a1, [__v6, #0]
	str	__a2, [__v6, #4]
	str	__a3, [__v6, #8]
	ldr	__a1, [__v6, #0]
	bl	|png_get_io_ptr|
	mov	__ip, __a1
	ldr	__a1, [__v6, #4]
	ldr	__a2, [__v6, #8]
	mov	__a3, __ip
	bl	|gdPutBuf|
|L..7|
	ldmea	__fp, {__v6, __fp, __sp, __pc}^
	ALIGN
	DCB &67, &64, &50, &6e
	DCB &67, &46, &6c, &75
	DCB &73, &68, &44, &61
	DCB &74, &61, &00
	ALIGN
	DCD	-16777200
|gdPngFlushData|
	KEEP |gdPngFlushData|
	; args = 0, pretend = 0, frame = 4, alloca = 0
	; frame_needed = 1, anonymous_args = 0, regs_live[14] = 0
	; nonlocal_label = 0, nonlocal_goto = 0, clobbers lr = 0
	mov	__ip, __sp
	stmfd	__sp!, {__v6, __fp, __ip, __lr, __pc}
	sub	__fp, __ip, #4
	cmp	__sp, __sl
	IMPORT	|__rt_stkovf_split_small|
	bllt	|__rt_stkovf_split_small|
	sub	__sp, __sp, #4
	mov	__v6, __sp
	str	__a1, [__v6, #0]
|L..8|
	ldmea	__fp, {__v6, __fp, __sp, __pc}^
	ALIGN
	EXPORT	|gdImageCreateFromPng|
	DCB &67, &64, &49, &6d
	DCB &61, &67, &65, &43
	DCB &72, &65, &61, &74
	DCB &65, &46, &72, &6f
	DCB &6d, &50, &6e, &67
	DCB &00
	ALIGN
	DCD	-16777192
|gdImageCreateFromPng|
	; args = 0, pretend = 0, frame = 12, alloca = 0
	; frame_needed = 1, anonymous_args = 0, regs_live[14] = 0
	; nonlocal_label = 0, nonlocal_goto = 0, clobbers lr = 1
	mov	__ip, __sp
	stmfd	__sp!, {__v6, __fp, __ip, __lr, __pc}
	sub	__fp, __ip, #4
	cmp	__sp, __sl
	IMPORT	|__rt_stkovf_split_small|
	bllt	|__rt_stkovf_split_small|
	sub	__sp, __sp, #12
	mov	__v6, __sp
	str	__a1, [__v6, #0]
	ldr	__a1, [__v6, #0]
	bl	|gdNewFileCtx|
	mov	__ip, __a1
	str	__ip, [__v6, #8]
	ldr	__a1, [__v6, #8]
	bl	|gdImageCreateFromPngCtx|
	mov	__ip, __a1
	str	__ip, [__v6, #4]
	ldr	__ip, [__v6, #8]
	ldr	__a3, [__ip, #24]
	ldr	__a1, [__v6, #8]
	mov	__lr, __pc
	mov	__pc, __a3
	ldr	__ip, [__v6, #4]
	mov	__a1, __ip
	b	|L..9|
|L..9|
	ldmea	__fp, {__v6, __fp, __sp, __pc}^
	ALIGN
|LC..2|
	DCB &31, &2e, &32, &2e
	DCB &30, &00
	ALIGN
|LC..3|
	DCB &67, &64, &2d, &70
	DCB &6e, &67, &20, &65
	DCB &72, &72, &6f, &72
	DCB &3a, &20, &63, &61
	DCB &6e, &6e, &6f, &74
	DCB &20, &61, &6c, &6c
	DCB &6f, &63, &61, &74
	DCB &65, &20, &6c, &69
	DCB &62, &70, &6e, &67
	DCB &20, &6d, &61, &69
	DCB &6e, &20, &73, &74
	DCB &72, &75, &63, &74
	DCB &0a, &00
	ALIGN
|LC..4|
	DCB &67, &64, &2d, &70
	DCB &6e, &67, &20, &65
	DCB &72, &72, &6f, &72
	DCB &3a, &20, &63, &61
	DCB &6e, &6e, &6f, &74
	DCB &20, &61, &6c, &6c
	DCB &6f, &63, &61, &74
	DCB &65, &20, &6c, &69
	DCB &62, &70, &6e, &67
	DCB &20, &69, &6e, &66
	DCB &6f, &20, &73, &74
	DCB &72, &75, &63, &74
	DCB &0a, &00
	ALIGN
|LC..5|
	DCB &67, &64, &2d, &70
	DCB &6e, &67, &20, &65
	DCB &72, &72, &6f, &72
	DCB &3a, &20, &73, &65
	DCB &74, &6a, &6d, &70
	DCB &20, &72, &65, &74
	DCB &75, &72, &6e, &73
	DCB &20, &65, &72, &72
	DCB &6f, &72, &20, &63
	DCB &6f, &6e, &64, &69
	DCB &74, &69, &6f, &6e
	DCB &0a, &00
	ALIGN
|LC..6|
	DCB &67, &64, &2d, &70
	DCB &6e, &67, &20, &77
	DCB &61, &72, &6e, &69
	DCB &6e, &67, &3a, &20
	DCB &61, &6c, &70, &68
	DCB &61, &20, &63, &68
	DCB &61, &6e, &6e, &65
	DCB &6c, &20, &6e, &6f
	DCB &74, &20, &73, &75
	DCB &70, &70, &6f, &72
	DCB &74, &65, &64, &0a
	DCB &00
	ALIGN
|LC..7|
	DCB &67, &64, &2d, &70
	DCB &6e, &67, &20, &77
	DCB &61, &72, &6e, &69
	DCB &6e, &67, &3a, &20
	DCB &6f, &6e, &6c, &79
	DCB &20, &73, &69, &6e
	DCB &67, &6c, &65, &2d
	DCB &63, &6f, &6c, &6f
	DCB &72, &2c, &20, &31
	DCB &30, &30, &25, &25
	DCB &20, &74, &72, &61
	DCB &6e, &73, &70, &61
	DCB &72, &65, &6e, &63
	DCB &79, &20, &73, &75
	DCB &70, &70, &6f, &72
	DCB &74, &65, &64, &0a
	DCB &00
	ALIGN
|LC..8|
	DCB &67, &64, &2d, &70
	DCB &6e, &67, &20, &65
	DCB &72, &72, &6f, &72
	DCB &3a, &20, &63, &61
	DCB &6e, &6e, &6f, &74
	DCB &20, &61, &6c, &6c
	DCB &6f, &63, &61, &74
	DCB &65, &20, &67, &72
	DCB &61, &79, &20, &70
	DCB &61, &6c, &65, &74
	DCB &74, &65, &0a, &00
	IMPORT	|__divsi3|
	ALIGN
|LC..9|
	DCB &67, &64, &2d, &70
	DCB &6e, &67, &20, &65
	DCB &72, &72, &6f, &72
	DCB &3a, &20, &63, &61
	DCB &6e, &6e, &6f, &74
	DCB &20, &61, &6c, &6c
	DCB &6f, &63, &61, &74
	DCB &65, &20, &52, &47
	DCB &42, &20, &70, &61
	DCB &6c, &65, &74, &74
	DCB &65, &0a, &00
	ALIGN
|LC..10|
	DCB &67, &64, &2d, &70
	DCB &6e, &67, &20, &65
	DCB &72, &72, &6f, &72
	DCB &3a, &20, &63, &61
	DCB &6e, &6e, &6f, &74
	DCB &20, &61, &6c, &6c
	DCB &6f, &63, &61, &74
	DCB &65, &20, &69, &6d
	DCB &61, &67, &65, &20
	DCB &64, &61, &74, &61
	DCB &0a, &00
	ALIGN
|LC..11|
	DCB &67, &64, &2d, &70
	DCB &6e, &67, &20, &65
	DCB &72, &72, &6f, &72
	DCB &3a, &20, &63, &61
	DCB &6e, &6e, &6f, &74
	DCB &20, &61, &6c, &6c
	DCB &6f, &63, &61, &74
	DCB &65, &20, &72, &6f
	DCB &77, &20, &70, &6f
	DCB &69, &6e, &74, &65
	DCB &72, &73, &0a, &00
	ALIGN
|LC..12|
	DCB &67, &64, &2d, &70
	DCB &6e, &67, &20, &65
	DCB &72, &72, &6f, &72
	DCB &3a, &20, &63, &61
	DCB &6e, &6e, &6f, &74
	DCB &20, &61, &6c, &6c
	DCB &6f, &63, &61, &74
	DCB &65, &20, &67, &64
	DCB &49, &6d, &61, &67
	DCB &65, &20, &73, &74
	DCB &72, &75, &63, &74
	DCB &0a, &00
	ALIGN
	EXPORT	|gdImageCreateFromPngCtx|
	DCB &67, &64, &49, &6d
	DCB &61, &67, &65, &43
	DCB &72, &65, &61, &74
	DCB &65, &46, &72, &6f
	DCB &6d, &50, &6e, &67
	DCB &43, &74, &78, &00
	ALIGN
	DCD	-16777192
|gdImageCreateFromPngCtx|
	; args = 0, pretend = 0, frame = 132, alloca = 0
	; frame_needed = 1, anonymous_args = 0, regs_live[14] = 0
	; nonlocal_label = 0, nonlocal_goto = 0, clobbers lr = 1
	mov	__ip, __sp
	stmfd	__sp!, {__v6, __fp, __ip, __lr, __pc}
	sub	__fp, __ip, #4
	cmp	__sp, __sl
	IMPORT	|__rt_stkovf_split_small|
	bllt	|__rt_stkovf_split_small|
	sub	__sp, __sp, #132
	mov	__v6, __sp
	str	__a1, [__v6, #20]
	mov	__ip, #0
	str	__ip, [__v6, #84]
	mov	__ip, #0
	str	__ip, [__v6, #88]
	mov	__ip, #0
	str	__ip, [__v6, #92]
	mvn	__ip, #0
	str	__ip, [__v6, #108]
	mov	__ip, #0
	str	__ip, [__v6, #112]
	ldr	__a1, [__v6, #20]
	mov	__a2, #0
	mov	__a3, #4
	bl	|memset|
	add	__ip, __v6, #24
	mov	__a1, __ip
	mov	__a2, #8
	ldr	__a3, [__v6, #20]
	bl	|gdGetBuf|
	add	__ip, __v6, #24
	mov	__a1, __ip
	mov	__a2, #8
	bl	|png_check_sig|
	mov	__ip, __a1
	cmp	__ip, #0
	bne	|L..11|
	mov	__a1, #0
	b	|L..10|
|L..11|
	ldr	__a1, |L..94|
	ldr	__a2, |L..94|+4
	ldr	__a3, |L..94|+8
	mov	__a4, #0
	bl	|png_create_read_struct|
	mov	__ip, __a1
	str	__ip, [__v6, #32]
	ldr	__ip, [__v6, #32]
	cmp	__ip, #0
	bne	|L..12|
	ldr	__ip, |L..94|+12
	ldr	__a1, [__ip, #0]
	ldr	__a2, |L..94|+16
	bl	|fprintf|
	mov	__a1, #0
	b	|L..10|
|L..12|
	ldr	__a1, [__v6, #32]
	bl	|png_create_info_struct|
	mov	__ip, __a1
	str	__ip, [__v6, #36]
	ldr	__ip, [__v6, #36]
	cmp	__ip, #0
	bne	|L..13|
	ldr	__ip, |L..94|+12
	ldr	__a1, [__ip, #0]
	ldr	__a2, |L..94|+20
	bl	|fprintf|
	add	__ip, __v6, #32
	mov	__a1, __ip
	mov	__a2, #0
	mov	__a3, #0
	bl	|png_destroy_read_struct|
	mov	__a1, #0
	b	|L..10|
|L..13|
	ldr	__a1, |L..94|+4
	bl	|___arm_alloca_setjmp|
	mov	__ip, __a1
	cmp	__ip, #0
	beq	|L..14|
	ldr	__ip, |L..94|+12
	ldr	__a1, [__ip, #0]
	ldr	__a2, |L..94|+24
	bl	|fprintf|
	add	__ip, __v6, #32
	add	__a3, __v6, #36
	mov	__a1, __ip
	mov	__a2, __a3
	mov	__a3, #0
	bl	|png_destroy_read_struct|
	mov	__a1, #0
	b	|L..10|
|L..14|
	ldr	__a1, [__v6, #32]
	mov	__a2, #8
	bl	|png_set_sig_bytes|
	ldr	__a1, [__v6, #32]
	ldr	__a2, [__v6, #20]
	ldr	__a3, |L..94|+28
	bl	|png_set_read_fn|
	ldr	__a1, [__v6, #32]
	ldr	__a2, [__v6, #36]
	bl	|png_read_info|
	add	__ip, __v6, #40
	add	__a4, __v6, #44
	add	__a3, __v6, #52
	str	__a3, [__sp, #0]
	add	__a3, __v6, #56
	str	__a3, [__sp, #4]
	add	__a3, __v6, #60
	str	__a3, [__sp, #8]
	mov	__a3, #0
	str	__a3, [__sp, #12]
	mov	__a3, #0
	str	__a3, [__sp, #16]
	ldr	__a1, [__v6, #32]
	ldr	__a2, [__v6, #36]
	mov	__a3, __ip
	bl	|png_get_IHDR|
	ldr	__ip, [__v6, #52]
	cmp	__ip, #16
	bne	|L..15|
	ldr	__a1, [__v6, #32]
	bl	|png_set_strip_16|
	b	|L..16|
|L..15|
	ldr	__ip, [__v6, #52]
	cmp	__ip, #7
	bgt	|L..16|
	ldr	__a1, [__v6, #32]
	bl	|png_set_packing|
|L..17|
|L..16|
	ldr	__a3, [__v6, #56]
	and	__ip, __a3, #4
	cmp	__ip, #0
	beq	|L..18|
	ldr	__ip, |L..94|+12
	ldr	__a1, [__ip, #0]
	ldr	__a2, |L..94|+32
	bl	|fprintf|
	ldr	__a1, [__v6, #32]
	bl	|png_set_strip_alpha|
|L..18|
	ldr	__ip, [__v6, #56]
	cmp	__ip, #6
	ldrls	__pc, [__pc, __ip, asl #2]
	b	|L..19|
	ALIGN
	ALIGN
|L..68|
	DCD	|L..34|
	DCD	|L..19|
	DCD	|L..50|
	DCD	|L..20|
	DCD	|L..34|
	DCD	|L..19|
	DCD	|L..50|
|L..20|
	add	__ip, __v6, #72
	add	__a4, __v6, #64
	ldr	__a1, [__v6, #32]
	ldr	__a2, [__v6, #36]
	mov	__a3, __ip
	bl	|png_get_PLTE|
	ldr	__a1, [__v6, #32]
	ldr	__a2, [__v6, #36]
	mov	__a3, #16
	bl	|png_get_valid|
	mov	__ip, __a1
	cmp	__ip, #0
	beq	|L..21|
	mov	__ip, #0
	str	__ip, [__v6, #116]
	mvn	__ip, #0
	str	__ip, [__v6, #120]
	mov	__ip, #256
	str	__ip, [__v6, #124]
	mvn	__ip, #0
	str	__ip, [__v6, #128]
	add	__ip, __v6, #80
	add	__a4, __v6, #68
	mov	__a3, #0
	str	__a3, [__sp, #0]
	ldr	__a1, [__v6, #32]
	ldr	__a2, [__v6, #36]
	mov	__a3, __ip
	bl	|png_get_tRNS|
	mov	__ip, #0
	str	__ip, [__v6, #96]
|L..22|
	ldr	__ip, [__v6, #96]
	ldr	__a3, [__v6, #68]
	cmp	__ip, __a3
	blt	|L..25|
	b	|L..23|
|L..25|
	ldr	__ip, [__v6, #80]
	ldr	__a3, [__v6, #96]
	add	__ip, __ip, __a3
	ldrb	__a3, [__ip, #0]	; zero_extendqisi2
	cmp	__a3, #254
	bhi	|L..24|
	ldr	__ip, [__v6, #116]
	add	__a3, __ip, #1
	str	__a3, [__v6, #116]
	ldr	__ip, [__v6, #120]
	cmp	__ip, #0
	bge	|L..27|
	ldr	__ip, [__v6, #96]
	str	__ip, [__v6, #120]
|L..27|
	ldr	__ip, [__v6, #80]
	ldr	__a3, [__v6, #96]
	add	__ip, __ip, __a3
	ldrb	__a3, [__ip, #0]	; zero_extendqisi2
	ldr	__ip, [__v6, #124]
	cmp	__a3, __ip
	bge	|L..24|
	ldr	__ip, [__v6, #80]
	ldr	__a3, [__v6, #96]
	add	__ip, __ip, __a3
	ldrb	__a3, [__ip, #0]	; zero_extendqisi2
	str	__a3, [__v6, #124]
	ldr	__ip, [__v6, #96]
	str	__ip, [__v6, #128]
|L..28|
|L..26|
|L..24|
	ldr	__ip, [__v6, #96]
	add	__a3, __ip, #1
	str	__a3, [__v6, #96]
	b	|L..22|
|L..23|
	ldr	__ip, [__v6, #116]
	cmp	__ip, #0
	ble	|L..21|
	ldr	__ip, [__v6, #116]
	cmp	__ip, #1
	bgt	|L..31|
	ldr	__ip, [__v6, #80]
	ldr	__a3, [__v6, #120]
	add	__ip, __ip, __a3
	ldrb	__a3, [__ip, #0]	; zero_extendqisi2
	cmp	__a3, #0
	bne	|L..31|
	b	|L..30|
|L..31|
	ldr	__ip, |L..94|+12
	ldr	__a1, [__ip, #0]
	ldr	__a2, |L..94|+36
	bl	|fprintf|
	ldr	__ip, [__v6, #128]
	str	__ip, [__v6, #108]
	b	|L..21|
|L..30|
	ldr	__ip, [__v6, #120]
	str	__ip, [__v6, #108]
|L..32|
|L..29|
|L..21|
	b	|L..19|
|L..33|
|L..34|
	mov	__a1, #1024
	bl	|gdMalloc|
	mov	__ip, __a1
	mov	__a3, __ip
	str	__a3, [__v6, #72]
	cmp	__a3, #0
	bne	|L..35|
	ldr	__ip, |L..94|+12
	ldr	__a1, [__ip, #0]
	ldr	__a2, |L..94|+40
	bl	|fprintf|
	add	__ip, __v6, #32
	add	__a3, __v6, #36
	mov	__a1, __ip
	mov	__a2, __a3
	mov	__a3, #0
	bl	|png_destroy_read_struct|
	mov	__a1, #0
	b	|L..10|
|L..35|
	mov	__ip, #1
	str	__ip, [__v6, #112]
	ldr	__ip, [__v6, #52]
	cmp	__ip, #7
	bgt	|L..36|
	mov	__ip, #1
	ldr	__a3, [__v6, #52]
	mov	__ip, __ip, asl __a3
	str	__ip, [__v6, #64]
	mov	__ip, #0
	str	__ip, [__v6, #96]
|L..37|
	ldr	__ip, [__v6, #96]
	cmp	__ip, #255
	ble	|L..40|
	b	|L..38|
|L..95|
	ALIGN
|L..94|
	DCD	|LC..2|
	DCD	|gdPngJmpbufStruct|
	DCD	|gdPngErrorHandler|
	DCD	|__stderr|
	DCD	|LC..3|
	DCD	|LC..4|
	DCD	|LC..5|
	DCD	|gdPngReadData|
	DCD	|LC..6|
	DCD	|LC..7|
	DCD	|LC..8|
|L..40|
	ldr	__a3, [__v6, #96]
	mov	__ip, __a3
	mov	__ip, __ip, asl #8
	rsb	__ip, __a3, __ip
	ldr	__a4, [__v6, #64]
	sub	__a3, __a4, #1
	mov	__a1, __ip
	mov	__a2, __a3
	bl	|__divsi3|
	mov	__ip, __a1
	str	__ip, [__v6, #100]
	ldr	__ip, [__v6, #96]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	ldr	__a3, [__v6, #72]
	add	__ip, __ip, __a3
	ldr	__a3, [__v6, #96]
	mov	__a4, __a3
	mov	__a3, __a4, asl #2
	ldr	__a4, [__v6, #72]
	add	__a3, __a3, __a4
	ldr	__a4, [__v6, #96]
	mov	__a2, __a4
	mov	__a4, __a2, asl #2
	ldr	__a2, [__v6, #72]
	add	__a4, __a4, __a2
	ldrb	__a2, [__v6, #100]
	strb	__a2, [__a4, #2]
	mov	__a4, __a2
	strb	__a4, [__a3, #1]
	strb	__a4, [__ip, #0]
|L..39|
	ldr	__ip, [__v6, #96]
	add	__a3, __ip, #1
	str	__a3, [__v6, #96]
	b	|L..37|
|L..38|
	b	|L..41|
|L..36|
	mov	__ip, #256
	str	__ip, [__v6, #64]
	mov	__ip, #0
	str	__ip, [__v6, #96]
|L..42|
	ldr	__ip, [__v6, #96]
	cmp	__ip, #255
	ble	|L..45|
	b	|L..41|
|L..45|
	ldr	__ip, [__v6, #96]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	ldr	__a3, [__v6, #72]
	add	__ip, __ip, __a3
	ldr	__a3, [__v6, #96]
	mov	__a4, __a3
	mov	__a3, __a4, asl #2
	ldr	__a4, [__v6, #72]
	add	__a3, __a3, __a4
	ldr	__a4, [__v6, #96]
	mov	__a2, __a4
	mov	__a4, __a2, asl #2
	ldr	__a2, [__v6, #72]
	add	__a4, __a4, __a2
	ldrb	__a2, [__v6, #96]
	strb	__a2, [__a4, #2]
	mov	__a4, __a2
	strb	__a4, [__a3, #1]
	strb	__a4, [__ip, #0]
|L..44|
	ldr	__ip, [__v6, #96]
	add	__a3, __ip, #1
	str	__a3, [__v6, #96]
	b	|L..42|
|L..43|
|L..41|
	ldr	__a1, [__v6, #32]
	ldr	__a2, [__v6, #36]
	mov	__a3, #16
	bl	|png_get_valid|
	mov	__ip, __a1
	cmp	__ip, #0
	beq	|L..46|
	add	__ip, __v6, #76
	str	__ip, [__sp, #0]
	ldr	__a1, [__v6, #32]
	ldr	__a2, [__v6, #36]
	mov	__a3, #0
	mov	__a4, #0
	bl	|png_get_tRNS|
	ldr	__ip, [__v6, #52]
	cmp	__ip, #16
	bne	|L..47|
	ldr	__ip, [__v6, #76]
	ldr	__a3, [__ip, #8]	; movhi
	mov	__a4, __a3, asl #16
	mov	__ip, __a4, lsr #16
	mov	__a3, __ip, lsr #8
	mov	__a4, __a3, asl #16
	mov	__ip, __a4, lsr #16
	str	__ip, [__v6, #108]
	b	|L..46|
|L..47|
	ldr	__ip, [__v6, #76]
	ldr	__a3, [__ip, #8]	; movhi
	mov	__a4, __a3, asl #16
	mov	__ip, __a4, lsr #16
	str	__ip, [__v6, #108]
|L..48|
|L..46|
	b	|L..19|
|L..49|
|L..50|
	mov	__a1, #1024
	bl	|gdMalloc|
	mov	__ip, __a1
	mov	__a3, __ip
	str	__a3, [__v6, #72]
	cmp	__a3, #0
	bne	|L..51|
	ldr	__ip, |L..96|
	ldr	__a1, [__ip, #0]
	ldr	__a2, |L..96|+4
	bl	|fprintf|
	add	__ip, __v6, #32
	add	__a3, __v6, #36
	mov	__a1, __ip
	mov	__a2, __a3
	mov	__a3, #0
	bl	|png_destroy_read_struct|
	mov	__a1, #0
	b	|L..10|
|L..51|
	mov	__ip, #1
	str	__ip, [__v6, #112]
	mov	__ip, #256
	str	__ip, [__v6, #64]
	ldr	__a1, [__v6, #32]
	ldr	__a2, [__v6, #36]
	mov	__a3, #16
	bl	|png_get_valid|
	mov	__ip, __a1
	cmp	__ip, #0
	beq	|L..52|
	add	__ip, __v6, #76
	str	__ip, [__sp, #0]
	ldr	__a1, [__v6, #32]
	ldr	__a2, [__v6, #36]
	mov	__a3, #0
	mov	__a4, #0
	bl	|png_get_tRNS|
	ldr	__ip, [__v6, #52]
	cmp	__ip, #16
	bne	|L..53|
	ldr	__ip, [__v6, #72]
	ldr	__a3, [__v6, #76]
	ldr	__a4, [__a3, #2]	; movhi
	mov	__a2, __a4, asl #16
	mov	__a3, __a2, lsr #16
	mov	__a4, __a3, lsr #8
	mov	__a3, __a4
	strb	__a3, [__ip, #0]
	ldr	__ip, [__v6, #72]
	ldr	__a3, [__v6, #76]
	ldr	__a4, [__a3, #4]	; movhi
	mov	__a2, __a4, asl #16
	mov	__a3, __a2, lsr #16
	mov	__a4, __a3, lsr #8
	mov	__a3, __a4
	strb	__a3, [__ip, #1]
	ldr	__ip, [__v6, #72]
	ldr	__a3, [__v6, #76]
	ldr	__a4, [__a3, #6]	; movhi
	mov	__a2, __a4, asl #16
	mov	__a3, __a2, lsr #16
	mov	__a4, __a3, lsr #8
	mov	__a3, __a4
	strb	__a3, [__ip, #2]
	b	|L..54|
|L..53|
	ldr	__ip, [__v6, #72]
	ldr	__a3, [__v6, #76]
	ldrb	__a4, [__a3, #2]
	strb	__a4, [__ip, #0]
	ldr	__ip, [__v6, #72]
	ldr	__a3, [__v6, #76]
	ldrb	__a4, [__a3, #4]
	strb	__a4, [__ip, #1]
	ldr	__ip, [__v6, #72]
	ldr	__a3, [__v6, #76]
	ldrb	__a4, [__a3, #6]
	strb	__a4, [__ip, #2]
|L..54|
	mov	__ip, #0
	str	__ip, [__v6, #108]
	b	|L..55|
|L..52|
	ldr	__ip, [__v6, #72]
	ldr	__a3, [__v6, #72]
	ldr	__a4, [__v6, #72]
	mov	__a2, #224
	mov	__a1, __a2
	strb	__a1, [__a4, #2]
	mov	__a4, #224
	mov	__a2, __a4
	strb	__a2, [__a3, #1]
	mov	__a3, #224
	mov	__a4, __a3
	strb	__a4, [__ip, #0]
|L..55|
	ldr	__a3, [__v6, #108]
	mvn	__ip, __a3
	mov	__a3, __ip, lsr #31
	str	__a3, [__v6, #128]
	mov	__ip, #0
	str	__ip, [__v6, #124]
|L..56|
	ldr	__ip, [__v6, #124]
	cmp	__ip, #255
	ble	|L..59|
	b	|L..57|
|L..59|
	mov	__ip, #0
	str	__ip, [__v6, #120]
|L..60|
	ldr	__ip, [__v6, #120]
	cmp	__ip, #255
	ble	|L..63|
	b	|L..58|
|L..63|
	mov	__ip, #0
	str	__ip, [__v6, #116]
|L..64|
	ldr	__ip, [__v6, #116]
	cmp	__ip, #255
	ble	|L..67|
	b	|L..62|
|L..67|
	ldr	__ip, [__v6, #128]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	ldr	__a3, [__v6, #72]
	add	__ip, __ip, __a3
	ldrb	__a3, [__v6, #124]
	strb	__a3, [__ip, #0]
	ldr	__ip, [__v6, #128]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	ldr	__a3, [__v6, #72]
	add	__ip, __ip, __a3
	ldrb	__a3, [__v6, #120]
	strb	__a3, [__ip, #1]
	ldr	__ip, [__v6, #128]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	ldr	__a3, [__v6, #72]
	add	__ip, __ip, __a3
	ldrb	__a3, [__v6, #116]
	strb	__a3, [__ip, #2]
	ldr	__ip, [__v6, #128]
	add	__a3, __ip, #1
	str	__a3, [__v6, #128]
|L..66|
	ldr	__ip, [__v6, #116]
	add	__a3, __ip, #51
	str	__a3, [__v6, #116]
	b	|L..64|
|L..65|
|L..62|
	ldr	__ip, [__v6, #120]
	add	__a3, __ip, #51
	str	__a3, [__v6, #120]
	b	|L..60|
|L..61|
|L..58|
	ldr	__ip, [__v6, #124]
	add	__a3, __ip, #51
	str	__a3, [__v6, #124]
	b	|L..56|
|L..57|
	mov	__ip, #0
	str	__ip, [__sp, #0]
	mov	__ip, #1
	str	__ip, [__sp, #4]
	ldr	__a1, [__v6, #32]
	ldr	__a2, [__v6, #72]
	ldr	__a3, [__v6, #128]
	ldr	__a4, [__v6, #128]
	bl	|png_set_dither|
	b	|L..19|
|L..69|
|L..19|
	ldr	__a1, [__v6, #32]
	ldr	__a2, [__v6, #36]
	bl	|png_read_update_info|
	ldr	__a1, [__v6, #32]
	ldr	__a2, [__v6, #36]
	bl	|png_get_rowbytes|
	mov	__ip, __a1
	str	__ip, [__v6, #48]
	ldr	__ip, [__v6, #48]
	ldr	__a3, [__v6, #44]
	mul	__ip, __a3, __ip
	mov	__a1, __ip
	bl	|gdMalloc|
	mov	__ip, __a1
	mov	__a3, __ip
	str	__a3, [__v6, #84]
	cmp	__a3, #0
	bne	|L..70|
	ldr	__ip, |L..96|
	ldr	__a1, [__ip, #0]
	ldr	__a2, |L..96|+8
	bl	|fprintf|
	add	__ip, __v6, #32
	add	__a3, __v6, #36
	mov	__a1, __ip
	mov	__a2, __a3
	mov	__a3, #0
	bl	|png_destroy_read_struct|
	mov	__a1, #0
	b	|L..10|
|L..70|
	ldr	__ip, [__v6, #44]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	mov	__a1, __ip
	bl	|gdMalloc|
	mov	__ip, __a1
	mov	__a3, __ip
	str	__a3, [__v6, #88]
	cmp	__a3, #0
	bne	|L..71|
	ldr	__ip, |L..96|
	ldr	__a1, [__ip, #0]
	ldr	__a2, |L..96|+12
	bl	|fprintf|
	add	__ip, __v6, #32
	add	__a3, __v6, #36
	mov	__a1, __ip
	mov	__a2, __a3
	mov	__a3, #0
	bl	|png_destroy_read_struct|
	ldr	__a1, [__v6, #84]
	bl	|gdFree|
	mov	__a1, #0
	b	|L..10|
|L..71|
	mov	__r0, __r0	; nop
	mov	__ip, #0
	str	__ip, [__v6, #100]
|L..72|
	ldr	__ip, [__v6, #100]
	ldr	__a3, [__v6, #44]
	cmp	__ip, __a3
	bcc	|L..75|
	b	|L..73|
|L..75|
	ldr	__ip, [__v6, #100]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	ldr	__a3, [__v6, #88]
	add	__ip, __ip, __a3
	ldr	__a3, [__v6, #100]
	ldr	__a4, [__v6, #48]
	mul	__a3, __a4, __a3
	ldr	__a4, [__v6, #84]
	add	__a3, __a4, __a3
	str	__a3, [__ip, #0]
|L..74|
	ldr	__ip, [__v6, #100]
	add	__a3, __ip, #1
	str	__a3, [__v6, #100]
	b	|L..72|
|L..97|
	ALIGN
|L..96|
	DCD	|__stderr|
	DCD	|LC..9|
	DCD	|LC..10|
	DCD	|LC..11|
|L..73|
	ldr	__a1, [__v6, #32]
	ldr	__a2, [__v6, #88]
	bl	|png_read_image|
	ldr	__a1, [__v6, #32]
	mov	__a2, #0
	bl	|png_read_end|
	ldr	__a1, [__v6, #40]
	ldr	__a2, [__v6, #44]
	bl	|gdImageCreate|
	mov	__ip, __a1
	str	__ip, [__v6, #92]
	ldr	__ip, [__v6, #92]
	cmp	__ip, #0
	bne	|L..76|
	ldr	__ip, |L..98|
	ldr	__a1, [__ip, #0]
	ldr	__a2, |L..98|+4
	bl	|fprintf|
	add	__ip, __v6, #32
	add	__a3, __v6, #36
	mov	__a1, __ip
	mov	__a2, __a3
	mov	__a3, #0
	bl	|png_destroy_read_struct|
	ldr	__a1, [__v6, #84]
	bl	|gdFree|
	ldr	__a1, [__v6, #88]
	bl	|gdFree|
	mov	__a1, #0
	b	|L..10|
|L..76|
	ldr	__ip, [__v6, #92]
	ldr	__a3, [__v6, #64]
	str	__a3, [__ip, #12]
	ldr	__ip, [__v6, #92]
	mov	__a3, #4096
	add	__a3, __a3, #16
	ldr	__a4, [__v6, #108]
	str	__a4, [__ip, __a3]
	ldr	__ip, [__v6, #92]
	mov	__a3, #6144
	add	__a3, __a3, #48
	ldr	__a4, [__v6, #60]
	cmp	__a4, #1
	movne	__a4, #0
	moveq	__a4, #1
	str	__a4, [__ip, __a3]
	ldr	__ip, [__v6, #92]
	add	__a3, __ip, #3088
	str	__a3, [__v6, #104]
	mov	__ip, #0
	str	__ip, [__v6, #96]
|L..77|
	ldr	__ip, [__v6, #96]
	ldr	__a3, [__v6, #64]
	cmp	__ip, __a3
	blt	|L..80|
	b	|L..78|
|L..80|
	ldr	__a3, [__v6, #92]
	ldr	__ip, [__v6, #96]
	mov	__a4, __ip
	mov	__ip, __a4, asl #2
	add	__a3, __a3, #16
	ldr	__a4, [__v6, #96]
	mov	__a2, __a4
	mov	__a4, __a2, asl #2
	ldr	__a2, [__v6, #72]
	add	__a4, __a4, __a2
	ldrb	__a2, [__a4, #0]	; zero_extendqisi2
	str	__a2, [__a3, __ip]
	ldr	__a3, [__v6, #92]
	ldr	__ip, [__v6, #96]
	mov	__a4, __ip
	mov	__ip, __a4, asl #2
	add	__a3, __a3, #1040
	ldr	__a4, [__v6, #96]
	mov	__a2, __a4
	mov	__a4, __a2, asl #2
	ldr	__a2, [__v6, #72]
	add	__a4, __a4, __a2
	ldrb	__a2, [__a4, #1]	; zero_extendqisi2
	str	__a2, [__a3, __ip]
	ldr	__a3, [__v6, #92]
	ldr	__ip, [__v6, #96]
	mov	__a4, __ip
	mov	__ip, __a4, asl #2
	add	__a3, __a3, #2064
	ldr	__a4, [__v6, #96]
	mov	__a2, __a4
	mov	__a4, __a2, asl #2
	ldr	__a2, [__v6, #72]
	add	__a4, __a4, __a2
	ldrb	__a2, [__a4, #2]	; zero_extendqisi2
	str	__a2, [__a3, __ip]
	ldr	__ip, [__v6, #96]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	ldr	__a3, [__v6, #104]
	add	__ip, __ip, __a3
	mov	__a3, #1
	str	__a3, [__ip, #0]
|L..79|
	ldr	__ip, [__v6, #96]
	add	__a3, __ip, #1
	str	__a3, [__v6, #96]
	b	|L..77|
|L..78|
	mov	__r0, __r0	; nop
	ldr	__ip, [__v6, #64]
	str	__ip, [__v6, #96]
|L..81|
	ldr	__ip, [__v6, #96]
	cmp	__ip, #255
	ble	|L..84|
	b	|L..82|
|L..84|
	ldr	__ip, [__v6, #96]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	ldr	__a3, [__v6, #104]
	add	__ip, __ip, __a3
	mov	__a3, #1
	str	__a3, [__ip, #0]
|L..83|
	ldr	__ip, [__v6, #96]
	add	__a3, __ip, #1
	str	__a3, [__v6, #96]
	b	|L..81|
|L..82|
	add	__ip, __v6, #32
	add	__a3, __v6, #36
	mov	__a1, __ip
	mov	__a2, __a3
	mov	__a3, #0
	bl	|png_destroy_read_struct|
	mov	__ip, #0
	str	__ip, [__v6, #100]
|L..85|
	ldr	__ip, [__v6, #100]
	ldr	__a3, [__v6, #44]
	cmp	__ip, __a3
	bcc	|L..88|
	b	|L..86|
|L..88|
	mov	__ip, #0
	str	__ip, [__v6, #96]
|L..89|
	ldr	__ip, [__v6, #96]
	ldr	__a3, [__v6, #40]
	cmp	__ip, __a3
	bcc	|L..92|
	b	|L..87|
|L..92|
	ldr	__a3, [__v6, #100]
	mov	__a4, __a3
	mov	__a3, __a4, asl #2
	ldr	__a4, [__v6, #88]
	add	__a3, __a3, __a4
	ldr	__a4, [__a3, #0]
	ldr	__a2, [__v6, #96]
	add	__a3, __a4, __a2
	ldrb	__a4, [__a3, #0]	; zero_extendqisi2
	mov	__ip, __a4
	ldr	__a3, [__v6, #92]
	ldr	__a4, [__v6, #100]
	mov	__a2, __a4
	mov	__a4, __a2, asl #2
	ldr	__a2, [__a3, #0]
	add	__a3, __a4, __a2
	ldr	__a4, [__a3, #0]
	ldr	__a2, [__v6, #96]
	add	__a3, __a4, __a2
	mov	__a4, __ip
	strb	__a4, [__a3, #0]
	mov	__a3, __ip
	mov	__a4, __a3, asl #2
	ldr	__a2, [__v6, #104]
	add	__a3, __a4, __a2
	mov	__a4, #0
	str	__a4, [__a3, #0]
|L..91|
	ldr	__ip, [__v6, #96]
	add	__a3, __ip, #1
	str	__a3, [__v6, #96]
	b	|L..89|
|L..90|
|L..87|
	ldr	__ip, [__v6, #100]
	add	__a3, __ip, #1
	str	__a3, [__v6, #100]
	b	|L..85|
|L..86|
	ldr	__ip, [__v6, #112]
	cmp	__ip, #0
	beq	|L..93|
	ldr	__a1, [__v6, #72]
	bl	|gdFree|
|L..93|
	ldr	__a1, [__v6, #84]
	bl	|gdFree|
	ldr	__a1, [__v6, #88]
	bl	|gdFree|
	ldr	__ip, [__v6, #92]
	mov	__a1, __ip
	b	|L..10|
|L..99|
	ALIGN
|L..98|
	DCD	|__stderr|
	DCD	|LC..12|
|L..10|
	ldmea	__fp, {__v6, __fp, __sp, __pc}^
	ALIGN
	EXPORT	|gdImagePng|
	DCB &67, &64, &49, &6d
	DCB &61, &67, &65, &50
	DCB &6e, &67, &00
	ALIGN
	DCD	-16777204
|gdImagePng|
	; args = 0, pretend = 0, frame = 12, alloca = 0
	; frame_needed = 1, anonymous_args = 0, regs_live[14] = 0
	; nonlocal_label = 0, nonlocal_goto = 0, clobbers lr = 1
	mov	__ip, __sp
	stmfd	__sp!, {__v6, __fp, __ip, __lr, __pc}
	sub	__fp, __ip, #4
	cmp	__sp, __sl
	IMPORT	|__rt_stkovf_split_small|
	bllt	|__rt_stkovf_split_small|
	sub	__sp, __sp, #12
	mov	__v6, __sp
	str	__a1, [__v6, #0]
	str	__a2, [__v6, #4]
	ldr	__a1, [__v6, #4]
	bl	|gdNewFileCtx|
	mov	__ip, __a1
	str	__ip, [__v6, #8]
	ldr	__a1, [__v6, #0]
	ldr	__a2, [__v6, #8]
	bl	|gdImagePngCtx|
	ldr	__ip, [__v6, #8]
	ldr	__a3, [__ip, #24]
	ldr	__a1, [__v6, #8]
	mov	__lr, __pc
	mov	__pc, __a3
|L..100|
	ldmea	__fp, {__v6, __fp, __sp, __pc}^
	ALIGN
	EXPORT	|gdImagePngPtr|
	DCB &67, &64, &49, &6d
	DCB &61, &67, &65, &50
	DCB &6e, &67, &50, &74
	DCB &72, &00
	ALIGN
	DCD	-16777200
|gdImagePngPtr|
	; args = 0, pretend = 0, frame = 16, alloca = 0
	; frame_needed = 1, anonymous_args = 0, regs_live[14] = 0
	; nonlocal_label = 0, nonlocal_goto = 0, clobbers lr = 1
	mov	__ip, __sp
	stmfd	__sp!, {__v6, __fp, __ip, __lr, __pc}
	sub	__fp, __ip, #4
	cmp	__sp, __sl
	IMPORT	|__rt_stkovf_split_small|
	bllt	|__rt_stkovf_split_small|
	sub	__sp, __sp, #16
	mov	__v6, __sp
	str	__a1, [__v6, #0]
	str	__a2, [__v6, #4]
	mov	__a1, #2048
	mov	__a2, #0
	bl	|gdNewDynamicCtx|
	mov	__ip, __a1
	str	__ip, [__v6, #12]
	ldr	__a1, [__v6, #0]
	ldr	__a2, [__v6, #12]
	bl	|gdImagePngCtx|
	ldr	__a1, [__v6, #12]
	ldr	__a2, [__v6, #4]
	bl	|gdDPExtractData|
	mov	__ip, __a1
	str	__ip, [__v6, #8]
	ldr	__ip, [__v6, #12]
	ldr	__a3, [__ip, #24]
	ldr	__a1, [__v6, #12]
	mov	__lr, __pc
	mov	__pc, __a3
	ldr	__ip, [__v6, #8]
	mov	__a1, __ip
	b	|L..101|
|L..101|
	ldmea	__fp, {__v6, __fp, __sp, __pc}^
	ALIGN
|LC..13|
	DCB &67, &64, &2d, &70
	DCB &6e, &67, &20, &65
	DCB &72, &72, &6f, &72
	DCB &3a, &20, &75, &6e
	DCB &61, &62, &6c, &65
	DCB &20, &74, &6f, &20
	DCB &61, &6c, &6c, &6f
	DCB &63, &61, &74, &65
	DCB &20, &72, &6f, &77
	DCB &5f, &70, &6f, &69
	DCB &6e, &74, &65, &72
	DCB &73, &0a, &00
	ALIGN
|LC..14|
	DCB &67, &64, &2d, &70
	DCB &6e, &67, &20, &65
	DCB &72, &72, &6f, &72
	DCB &3a, &20, &75, &6e
	DCB &61, &62, &6c, &65
	DCB &20, &74, &6f, &20
	DCB &61, &6c, &6c, &6f
	DCB &63, &61, &74, &65
	DCB &20, &72, &6f, &77
	DCB &73, &0a, &00
	ALIGN
	EXPORT	|gdImagePngCtx|
	DCB &67, &64, &49, &6d
	DCB &61, &67, &65, &50
	DCB &6e, &67, &43, &74
	DCB &78, &00
	ALIGN
	DCD	-16777200
|gdImagePngCtx|
	; args = 0, pretend = 0, frame = 2132, alloca = 0
	; frame_needed = 1, anonymous_args = 0, regs_live[14] = 0
	; nonlocal_label = 0, nonlocal_goto = 0, clobbers lr = 1
	mov	__ip, __sp
	stmfd	__sp!, {__v6, __fp, __ip, __lr, __pc}
	sub	__fp, __ip, #4
	sub	__ip, __sp, #2128
	cmp	__ip, __sl
	IMPORT	|__rt_stkovf_split_big|
	bllt	|__rt_stkovf_split_big|
	sub	__sp, __sp, #84
	sub	__sp, __sp, #2048
	mov	__v6, __sp
	str	__a1, [__v6, #20]
	str	__a2, [__v6, #24]
	ldr	__ip, [__v6, #20]
	ldr	__a3, [__ip, #4]
	str	__a3, [__v6, #44]
	ldr	__ip, [__v6, #20]
	ldr	__a3, [__ip, #8]
	str	__a3, [__v6, #48]
	ldr	__ip, [__v6, #20]
	ldr	__a3, [__ip, #12]
	str	__a3, [__v6, #52]
	ldr	__ip, [__v6, #20]
	add	__a3, __ip, #3088
	str	__a3, [__v6, #56]
	mov	__ip, #0
	mov	__a3, __ip
	strb	__a3, [__v6, #1084]
	ldr	__ip, [__v6, #20]
	mov	__a3, #4096
	add	__a3, __a3, #16
	ldr	__ip, [__ip, __a3]
	str	__ip, [__v6, #2120]
	mov	__ip, #0
	str	__ip, [__v6, #2124]
	ldr	__a1, |L..163|
	ldr	__a2, |L..163|+4
	ldr	__a3, |L..163|+8
	mov	__a4, #0
	bl	|png_create_write_struct|
	mov	__ip, __a1
	str	__ip, [__v6, #2112]
	ldr	__ip, [__v6, #2112]
	cmp	__ip, #0
	bne	|L..103|
	ldr	__ip, |L..163|+12
	ldr	__a1, [__ip, #0]
	ldr	__a2, |L..163|+16
	bl	|fprintf|
	b	|L..102|
|L..103|
	ldr	__a1, [__v6, #2112]
	bl	|png_create_info_struct|
	mov	__ip, __a1
	str	__ip, [__v6, #2116]
	ldr	__ip, [__v6, #2116]
	cmp	__ip, #0
	bne	|L..104|
	ldr	__ip, |L..163|+12
	ldr	__a1, [__ip, #0]
	ldr	__a2, |L..163|+20
	bl	|fprintf|
	add	__ip, __v6, #2096
	add	__ip, __ip, #4
	add	__ip, __ip, #12
	mov	__a1, __ip
	mov	__a2, #0
	bl	|png_destroy_write_struct|
	b	|L..102|
|L..104|
	ldr	__a1, |L..163|+4
	bl	|___arm_alloca_setjmp|
	mov	__ip, __a1
	cmp	__ip, #0
	beq	|L..105|
	ldr	__ip, |L..163|+12
	ldr	__a1, [__ip, #0]
	ldr	__a2, |L..163|+24
	bl	|fprintf|
	add	__ip, __v6, #2096
	add	__ip, __ip, #4
	add	__ip, __ip, #12
	add	__a3, __v6, #2112
	add	__a3, __a3, #4
	mov	__a1, __ip
	mov	__a2, __a3
	bl	|png_destroy_write_struct|
	b	|L..102|
|L..105|
	ldr	__a1, [__v6, #2112]
	ldr	__a2, [__v6, #24]
	ldr	__a3, |L..163|+28
	ldr	__a4, |L..163|+32
	bl	|png_set_write_fn|
	ldr	__ip, [__v6, #20]
	ldr	__a3, [__v6, #2120]
	ldr	__ip, [__ip, #12]
	cmp	__a3, __ip
	bge	|L..107|
	ldr	__ip, [__v6, #2120]
	cmp	__ip, #0
	blt	|L..106|
	ldr	__ip, [__v6, #2120]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	ldr	__a3, [__v6, #56]
	add	__ip, __ip, __a3
	ldr	__a3, [__ip, #0]
	cmp	__a3, #0
	bne	|L..107|
	b	|L..106|
|L..107|
	mvn	__ip, #0
	str	__ip, [__v6, #2120]
|L..106|
	mov	__r0, __r0	; nop
	mov	__ip, #0
	str	__ip, [__v6, #28]
|L..108|
	ldr	__ip, [__v6, #28]
	cmp	__ip, #255
	ble	|L..111|
	b	|L..109|
|L..111|
	ldr	__ip, [__v6, #28]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	add	__a3, __v6, #60
	mvn	__a4, #0
	str	__a4, [__a3, __ip]
|L..110|
	ldr	__ip, [__v6, #28]
	add	__a3, __ip, #1
	str	__a3, [__v6, #28]
	b	|L..108|
|L..109|
	mov	__ip, #0
	str	__ip, [__v6, #52]
	mov	__ip, #0
	str	__ip, [__v6, #28]
|L..112|
	ldr	__ip, [__v6, #20]
	ldr	__a3, [__v6, #28]
	ldr	__ip, [__ip, #12]
	cmp	__a3, __ip
	blt	|L..115|
	b	|L..113|
|L..115|
	ldr	__ip, [__v6, #28]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	ldr	__a3, [__v6, #56]
	add	__ip, __ip, __a3
	ldr	__a3, [__ip, #0]
	cmp	__a3, #0
	bne	|L..114|
	ldr	__ip, [__v6, #28]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	add	__a3, __v6, #60
	ldr	__a4, [__v6, #52]
	str	__a4, [__a3, __ip]
	ldr	__ip, [__v6, #52]
	add	__a3, __ip, #1
	str	__a3, [__v6, #52]
|L..116|
|L..114|
	ldr	__ip, [__v6, #28]
	add	__a3, __ip, #1
	str	__a3, [__v6, #28]
	b	|L..112|
|L..113|
	ldr	__ip, [__v6, #20]
	ldr	__a3, [__v6, #52]
	ldr	__ip, [__ip, #12]
	cmp	__a3, __ip
	bge	|L..117|
	mov	__ip, #1
	str	__ip, [__v6, #2124]
	ldr	__ip, [__v6, #2120]
	cmp	__ip, #0
	blt	|L..117|
	ldr	__ip, [__v6, #2120]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	add	__a3, __v6, #60
	ldr	__ip, [__a3, __ip]
	str	__ip, [__v6, #2120]
|L..118|
|L..117|
	ldr	__ip, [__v6, #52]
	cmp	__ip, #2
	bgt	|L..119|
	mov	__ip, #1
	str	__ip, [__v6, #36]
	b	|L..120|
|L..119|
	ldr	__ip, [__v6, #52]
	cmp	__ip, #4
	bgt	|L..121|
	mov	__ip, #2
	str	__ip, [__v6, #36]
	b	|L..120|
|L..121|
	ldr	__ip, [__v6, #52]
	cmp	__ip, #16
	bgt	|L..123|
	mov	__ip, #4
	str	__ip, [__v6, #36]
	b	|L..120|
|L..123|
	mov	__ip, #8
	str	__ip, [__v6, #36]
|L..124|
|L..122|
|L..120|
	ldr	__ip, [__v6, #20]
	mov	__a3, #6144
	add	__a3, __a3, #48
	ldr	__ip, [__ip, __a3]
	cmp	__ip, #0
	moveq	__ip, #0
	movne	__ip, #1
	str	__ip, [__v6, #40]
	ldr	__ip, [__v6, #36]
	str	__ip, [__sp, #0]
	mov	__ip, #3
	str	__ip, [__sp, #4]
	ldr	__ip, [__v6, #40]
	str	__ip, [__sp, #8]
	mov	__ip, #0
	str	__ip, [__sp, #12]
	mov	__ip, #0
	str	__ip, [__sp, #16]
	ldr	__a1, [__v6, #2112]
	ldr	__a2, [__v6, #2116]
	ldr	__a3, [__v6, #44]
	ldr	__a4, [__v6, #48]
	bl	|png_set_IHDR|
	ldr	__ip, [__v6, #2120]
	cmp	__ip, #0
	blt	|L..125|
	ldr	__ip, [__v6, #2120]
	cmp	__ip, #0
	beq	|L..126|
	ldr	__ip, [__v6, #2124]
	cmp	__ip, #0
	bne	|L..127|
	mov	__ip, #1
	str	__ip, [__v6, #2124]
	mov	__ip, #0
	str	__ip, [__v6, #28]
|L..128|
	ldr	__ip, [__v6, #28]
	ldr	__a3, [__v6, #52]
	cmp	__ip, __a3
	blt	|L..131|
	b	|L..127|
|L..131|
	ldr	__ip, [__v6, #28]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	add	__a3, __v6, #60
	ldr	__a4, [__v6, #28]
	str	__a4, [__a3, __ip]
|L..130|
	ldr	__ip, [__v6, #28]
	add	__a3, __ip, #1
	str	__a3, [__v6, #28]
	b	|L..128|
|L..129|
|L..127|
	ldr	__ip, [__v6, #2120]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	add	__a3, __v6, #60
	mov	__a4, #0
	str	__a4, [__a3, __ip]
	ldr	__ip, [__v6, #2120]
	str	__ip, [__v6, #60]
|L..126|
	add	__ip, __v6, #1072
	add	__ip, __ip, #4
	add	__ip, __ip, #8
	mov	__a3, #0
	str	__a3, [__sp, #0]
	ldr	__a1, [__v6, #2112]
	ldr	__a2, [__v6, #2116]
	mov	__a3, __ip
	mov	__a4, #1
	bl	|png_set_tRNS|
|L..125|
	ldr	__ip, [__v6, #2124]
	cmp	__ip, #0
	beq	|L..132|
	mov	__ip, #0
	str	__ip, [__v6, #28]
|L..133|
	ldr	__ip, [__v6, #20]
	ldr	__a3, [__v6, #28]
	ldr	__ip, [__ip, #12]
	cmp	__a3, __ip
	blt	|L..136|
	b	|L..134|
|L..164|
	ALIGN
|L..163|
	DCD	|LC..2|
	DCD	|gdPngJmpbufStruct|
	DCD	|gdPngErrorHandler|
	DCD	|__stderr|
	DCD	|LC..3|
	DCD	|LC..4|
	DCD	|LC..5|
	DCD	|gdPngWriteData|
	DCD	|gdPngFlushData|
|L..136|
	ldr	__ip, [__v6, #28]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	add	__a3, __v6, #60
	ldr	__ip, [__a3, __ip]
	cmp	__ip, #0
	bge	|L..137|
	b	|L..135|
|L..137|
	ldr	__ip, [__v6, #28]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	add	__a3, __v6, #60
	ldr	__ip, [__a3, __ip]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	add	__a3, __v6, #20
	add	__ip, __a3, __ip
	ldr	__a3, [__v6, #20]
	ldr	__a4, [__v6, #28]
	mov	__a2, __a4
	mov	__a4, __a2, asl #2
	add	__a3, __a3, #16
	ldrb	__a4, [__a3, __a4]
	strb	__a4, [__ip, #1068]
	ldr	__ip, [__v6, #28]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	add	__a3, __v6, #60
	ldr	__ip, [__a3, __ip]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	add	__a3, __v6, #20
	add	__ip, __a3, __ip
	ldr	__a3, [__v6, #20]
	ldr	__a4, [__v6, #28]
	mov	__a2, __a4
	mov	__a4, __a2, asl #2
	add	__a3, __a3, #1040
	ldrb	__a4, [__a3, __a4]
	strb	__a4, [__ip, #1069]
	ldr	__ip, [__v6, #28]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	add	__a3, __v6, #60
	ldr	__ip, [__a3, __ip]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	add	__a3, __v6, #20
	add	__ip, __a3, __ip
	ldr	__a3, [__v6, #20]
	ldr	__a4, [__v6, #28]
	mov	__a2, __a4
	mov	__a4, __a2, asl #2
	add	__a3, __a3, #2064
	ldrb	__a4, [__a3, __a4]
	strb	__a4, [__ip, #1070]
|L..135|
	ldr	__ip, [__v6, #28]
	add	__a3, __ip, #1
	str	__a3, [__v6, #28]
	b	|L..133|
|L..134|
	b	|L..138|
|L..132|
	mov	__r0, __r0	; nop
	mov	__ip, #0
	str	__ip, [__v6, #28]
|L..139|
	ldr	__ip, [__v6, #28]
	ldr	__a3, [__v6, #52]
	cmp	__ip, __a3
	blt	|L..142|
	b	|L..138|
|L..142|
	ldr	__ip, [__v6, #28]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	add	__a3, __v6, #20
	add	__ip, __a3, __ip
	ldr	__a3, [__v6, #20]
	ldr	__a4, [__v6, #28]
	mov	__a2, __a4
	mov	__a4, __a2, asl #2
	add	__a3, __a3, #16
	ldrb	__a4, [__a3, __a4]
	strb	__a4, [__ip, #1068]
	ldr	__ip, [__v6, #28]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	add	__a3, __v6, #20
	add	__ip, __a3, __ip
	ldr	__a3, [__v6, #20]
	ldr	__a4, [__v6, #28]
	mov	__a2, __a4
	mov	__a4, __a2, asl #2
	add	__a3, __a3, #1040
	ldrb	__a4, [__a3, __a4]
	strb	__a4, [__ip, #1069]
	ldr	__ip, [__v6, #28]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	add	__a3, __v6, #20
	add	__ip, __a3, __ip
	ldr	__a3, [__v6, #20]
	ldr	__a4, [__v6, #28]
	mov	__a2, __a4
	mov	__a4, __a2, asl #2
	add	__a3, __a3, #2064
	ldrb	__a4, [__a3, __a4]
	strb	__a4, [__ip, #1070]
|L..141|
	ldr	__ip, [__v6, #28]
	add	__a3, __ip, #1
	str	__a3, [__v6, #28]
	b	|L..139|
|L..140|
|L..138|
	add	__ip, __v6, #1072
	add	__ip, __ip, #4
	add	__ip, __ip, #12
	ldr	__a1, [__v6, #2112]
	ldr	__a2, [__v6, #2116]
	mov	__a3, __ip
	ldr	__a4, [__v6, #52]
	bl	|png_set_PLTE|
	ldr	__a1, [__v6, #2112]
	ldr	__a2, [__v6, #2116]
	bl	|png_write_info|
	ldr	__a1, [__v6, #2112]
	bl	|png_set_packing|
	ldr	__ip, [__v6, #2124]
	cmp	__ip, #0
	beq	|L..143|
	ldr	__ip, [__v6, #48]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	mov	__a1, __ip
	bl	|gdMalloc|
	str	__a1, [__v6, #2128]
	ldr	__ip, [__v6, #2128]
	cmp	__ip, #0
	bne	|L..144|
	ldr	__ip, |L..165|
	ldr	__a1, [__ip, #0]
	ldr	__a2, |L..165|+4
	bl	|fprintf|
|L..144|
	mov	__r0, __r0	; nop
	mov	__ip, #0
	str	__ip, [__v6, #32]
|L..145|
	ldr	__ip, [__v6, #32]
	ldr	__a3, [__v6, #48]
	cmp	__ip, __a3
	blt	|L..148|
	b	|L..146|
|L..148|
	ldr	__a1, [__v6, #44]
	bl	|gdMalloc|
	mov	__ip, __a1
	ldr	__a3, [__v6, #32]
	mov	__a4, __a3
	mov	__a3, __a4, asl #2
	ldr	__a4, [__v6, #2128]
	add	__a3, __a3, __a4
	str	__ip, [__a3, #0]
	cmp	__ip, #0
	bne	|L..149|
	ldr	__ip, |L..165|
	ldr	__a1, [__ip, #0]
	ldr	__a2, |L..165|+8
	bl	|fprintf|
	mov	__ip, #0
	str	__ip, [__v6, #28]
|L..150|
	ldr	__ip, [__v6, #28]
	ldr	__a3, [__v6, #32]
	cmp	__ip, __a3
	blt	|L..153|
	b	|L..151|
|L..153|
	ldr	__ip, [__v6, #28]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	ldr	__a3, [__v6, #2128]
	add	__ip, __ip, __a3
	ldr	__a1, [__ip, #0]
	bl	|gdFree|
|L..152|
	ldr	__ip, [__v6, #28]
	add	__a3, __ip, #1
	str	__a3, [__v6, #28]
	b	|L..150|
|L..151|
	b	|L..102|
|L..149|
	mov	__r0, __r0	; nop
	mov	__ip, #0
	str	__ip, [__v6, #28]
|L..154|
	ldr	__ip, [__v6, #28]
	ldr	__a3, [__v6, #44]
	cmp	__ip, __a3
	blt	|L..157|
	b	|L..147|
|L..157|
	ldr	__ip, [__v6, #32]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	ldr	__a3, [__v6, #2128]
	add	__ip, __ip, __a3
	ldr	__a3, [__ip, #0]
	ldr	__a4, [__v6, #28]
	add	__ip, __a3, __a4
	ldr	__a3, [__v6, #20]
	ldr	__a4, [__v6, #32]
	mov	__a2, __a4
	mov	__a4, __a2, asl #2
	ldr	__a2, [__a3, #0]
	add	__a3, __a4, __a2
	ldr	__a4, [__a3, #0]
	ldr	__a2, [__v6, #28]
	add	__a3, __a4, __a2
	ldrb	__a4, [__a3, #0]	; zero_extendqisi2
	mov	__a3, __a4
	mov	__a4, __a3, asl #2
	add	__a3, __v6, #60
	ldrb	__a4, [__a3, __a4]
	strb	__a4, [__ip, #0]
|L..156|
	ldr	__ip, [__v6, #28]
	add	__a3, __ip, #1
	str	__a3, [__v6, #28]
	b	|L..154|
|L..155|
|L..147|
	ldr	__ip, [__v6, #32]
	add	__a3, __ip, #1
	str	__a3, [__v6, #32]
	b	|L..145|
|L..146|
	ldr	__a1, [__v6, #2112]
	ldr	__a2, [__v6, #2128]
	bl	|png_write_image|
	ldr	__a1, [__v6, #2112]
	ldr	__a2, [__v6, #2116]
	bl	|png_write_end|
	mov	__ip, #0
	str	__ip, [__v6, #32]
|L..158|
	ldr	__ip, [__v6, #32]
	ldr	__a3, [__v6, #48]
	cmp	__ip, __a3
	blt	|L..161|
	b	|L..159|
|L..161|
	ldr	__ip, [__v6, #32]
	mov	__a3, __ip
	mov	__ip, __a3, asl #2
	ldr	__a3, [__v6, #2128]
	add	__ip, __ip, __a3
	ldr	__a1, [__ip, #0]
	bl	|gdFree|
|L..160|
	ldr	__ip, [__v6, #32]
	add	__a3, __ip, #1
	str	__a3, [__v6, #32]
	b	|L..158|
|L..159|
	ldr	__a1, [__v6, #2128]
	bl	|gdFree|
	b	|L..162|
|L..166|
	ALIGN
|L..165|
	DCD	|__stderr|
	DCD	|LC..13|
	DCD	|LC..14|
|L..143|
	ldr	__ip, [__v6, #20]
	ldr	__a1, [__v6, #2112]
	ldr	__a2, [__ip, #0]
	bl	|png_write_image|
	ldr	__a1, [__v6, #2112]
	ldr	__a2, [__v6, #2116]
	bl	|png_write_end|
|L..162|
	add	__ip, __v6, #2096
	add	__ip, __ip, #4
	add	__ip, __ip, #12
	add	__a3, __v6, #2112
	add	__a3, __a3, #4
	mov	__a1, __ip
	mov	__a2, __a3
	bl	|png_destroy_write_struct|
|L..102|
	ldmea	__fp, {__v6, __fp, __sp, __pc}^
	AREA |C$$zidata1|,NOINIT
|gdPngJmpbufStruct|
	% 100	; size=100
	IMPORT	|png_write_end|
	IMPORT	|png_write_image|
	IMPORT	|png_write_info|
	IMPORT	|png_set_PLTE|
	IMPORT	|png_set_tRNS|
	IMPORT	|png_set_IHDR|
	IMPORT	|png_set_write_fn|
	IMPORT	|png_destroy_write_struct|
	IMPORT	|png_create_write_struct|
	IMPORT	|gdDPExtractData|
	IMPORT	|gdNewDynamicCtx|
	IMPORT	|gdImageCreate|
	IMPORT	|png_read_end|
	IMPORT	|png_read_image|
	IMPORT	|gdFree|
	IMPORT	|png_get_rowbytes|
	IMPORT	|png_read_update_info|
	IMPORT	|png_set_dither|
	IMPORT	|gdMalloc|
	IMPORT	|png_get_tRNS|
	IMPORT	|png_get_valid|
	IMPORT	|png_get_PLTE|
	IMPORT	|png_set_strip_alpha|
	IMPORT	|png_set_packing|
	IMPORT	|png_set_strip_16|
	IMPORT	|png_get_IHDR|
	IMPORT	|png_read_info|
	IMPORT	|png_set_read_fn|
	IMPORT	|png_set_sig_bytes|
	IMPORT	|setjmp|
	IMPORT	|png_destroy_read_struct|
	IMPORT	|png_create_info_struct|
	IMPORT	|png_create_read_struct|
	IMPORT	|png_check_sig|
	IMPORT	|memset|
	IMPORT	|gdNewFileCtx|
	IMPORT	|gdPutBuf|
	IMPORT	|png_get_io_ptr|
	IMPORT	|gdGetBuf|
	IMPORT	|longjmp|
	IMPORT	|exit|
	IMPORT	|png_get_error_ptr|
	IMPORT	|fflush|
	IMPORT	|__stderr|
	IMPORT	|fprintf|
	END
